<a href="https://colab.research.google.com/github/windyday0622/windyday/blob/main/m3_%EB%B6%84%EC%84%9D%20%EB%9D%BC%EC%9D%B4%EB%B8%8C%EB%9F%AC%EB%A6%AC/%20numpy_quiz1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy Quiz1

Q1. arange(), reshape() 이용 1차원 2차원 3차원 배열 생성

In [ ]:
import numpy as np

array_1d = np.arange(10)
print("1차원 배열:\n", array_1d)

array_2d = array_1d.reshape((2, 5))
print("2차원 배열:\n", array_2d)

array_3d = array_1d.reshape((1, 2, 5))
print("3차원 배열:\n", array_3d)

1차원 배열:
 [0 1 2 3 4 5 6 7 8 9]
2차원 배열:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
3차원 배열:
 [[[0 1 2 3 4]
  [5 6 7 8 9]]]


Q2. reshape(-1,-1)을 이용 1차원을 2차원, 3차원으로 2차원을 1차원 3차원으로 3차원을 1차원 2차원으로 변환

In [ ]:
import numpy as np

array_1d = np.array([1, 2, 3, 4, 5, 6])

array_2d = array_1d.reshape(2, 3)
print(array_2d)

array_3d = array_1d.reshape(2, 1, 3)
print(array_3d)


array_2d = np.array([[1, 2, 3], [4, 5, 6]])

array_1d = array_2d.reshape(-1)
print(array_1d)

array_3d = array_2d.reshape(2, 1, 3)
print(array_3d)


array_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

array_1d = array_3d.reshape(-1)
print(array_1d)

array_2d = array_3d.reshape(4, 3)
print(array_2d)

[[1 2 3]
 [4 5 6]]
[[[1 2 3]]

 [[4 5 6]]]
[1 2 3 4 5 6]
[[[1 2 3]]

 [[4 5 6]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


Q3. Q1 1차원 배열을 실수형으로 변환

In [ ]:
import numpy as np

array_1d = np.arange(10)

float_array_1d = array_1d.astype(float)

print("실수형 1차원 배열:\n", float_array_1d)

실수형 1차원 배열:
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


Q4. Q1 1차원 배열의 dtype을 확인

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr.dtype)

int64


Q5. 주어진 배열에서 음수 값을 모두 0으로 변경하세요.

arr = np.array([-5, -3, -1, 0, 1, 3, 5])

In [ ]:
import numpy as np

arr = np.array([-5, -3, -1, 0, 1, 3, 5])

arr[arr < 0] = 0

print(arr)

[0 0 0 0 1 3 5]


Q6. 1 ~ 100 까지 배열에서 3의 배수인 것만을 출력

In [ ]:
import numpy as np

array = np.arange(1, 101)

multiples_of_three = array[array % 3 == 0]

print(multiples_of_three)

[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72
 75 78 81 84 87 90 93 96 99]


Q7. 1 ~ 100 까지 배열에서 5의 배수이면서 2의 배수인 것만을 출력

In [ ]:
import numpy as np

arr = np.arange(1, 101)

result = arr[(arr % 5 == 0) & (arr % 2 == 0)]

print(result)

[ 10  20  30  40  50  60  70  80  90 100]


Q8. 1 ~ 100 까지 배열에서 3의 배수이거나 5의 배수인 것만을 출력

In [ ]:
for i in range(1, 101):
    if i % 3 == 0 or i % 5 == 0:
        print(i)

3
5
6
9
10
12
15
18
20
21
24
25
27
30
33
35
36
39
40
42
45
48
50
51
54
55
57
60
63
65
66
69
70
72
75
78
80
81
84
85
87
90
93
95
96
99
100


Q9. 101 ~ 150 사이의 정수를 랜덤하게 추출, 2행 5열 다차원 배열을 생성 후 전치하세요

In [ ]:
import numpy as np

random_numbers = np.random.randint(101, 151, size=10)

array_2x5 = random_numbers.reshape(2, 5)

transposed_array = array_2x5.T

print("원본 배열 (2행 5열):")
print(array_2x5)
print("\n전치된 배열 (5행 2열):")
print(transposed_array)

원본 배열 (2행 5열):
[[121 124 120 113 146]
 [102 113 117 134 108]]

전치된 배열 (5행 2열):
[[121 102]
 [124 113]
 [120 117]
 [113 134]
 [146 108]]


Q10. 표준정규분포로 구성된 5행 5열 다차원 배열을 생성하세요.

In [ ]:
import numpy as np

array = np.random.normal(loc=0, scale=1, size=(5, 5))

print(array)

[[-0.15201838  0.57609565  0.30375304 -0.25763831 -0.48922731]
 [ 1.11642113 -0.54032564 -0.60489979  0.00455034 -0.39557179]
 [-1.31929134 -0.76360369  0.91740771  0.46707944  1.09890379]
 [-0.49313465 -1.38670327 -1.87613324  0.509768   -0.65599905]
 [ 0.67961533  1.37987322  0.3717366   0.55160966  1.11092486]]


Q11. original_array를 1차원 배열로 변환하여 출력하세요.

In [ ]:
original_array = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
import numpy as np

original_array = np.array([[1, 2, 3], [4, 5, 6]])

flattened_array = original_array.flatten()

print(flattened_array)

[1 2 3 4 5 6]


Q12. 주어진 2차원 배열에서 첫 번째 행을 view로 생성하고, 이 view를 수정하여 원본 배열에 반영되도록 하세요.

original_array = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
import numpy as np

original_array = np.array([[1, 2, 3], [4, 5, 6]])

view_first_row = original_array[0, :]

view_first_row[0] = 10
view_first_row[1] = 20
view_first_row[2] = 30

print("수정된 원본 배열:")
print(original_array)

수정된 원본 배열:
[[10 20 30]
 [ 4  5  6]]


Q13. 주어진 3차원 배열에서 첫 번째 2차원 배열을 view로 생성하고, 이 view를 수정하여 원본 배열에 반영되도록 하세요.

original_array = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [ ]:
import numpy as np

original_array = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

first_2d_view = original_array[0]

first_2d_view[0, 0] = 99

print("수정된 원본 배열:")
print(original_array)

수정된 원본 배열:
[[[99  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


Q14. 주어진 2차원 배열을 1차원 배열 view로 reshape하고, 이 view를 수정하여 원본 배열에 반영되도록 하세요.

original_array = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
import numpy as np

original_array = np.array([[1, 2, 3], [4, 5, 6]])

reshaped_view = original_array.reshape(-1)

reshaped_view[0] = 10
reshaped_view[5] = 60

print("수정된 원본 배열:")
print(original_array)

수정된 원본 배열:
[[10  2  3]
 [ 4  5 60]]


Q15. np.ones((10,10))을 아래와 같이 출력하세요.
```
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
 ```

In [ ]:
import numpy as np

array = np.ones((10, 10))

array[1:-1, 1:-1] = 0

print(array)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


Q16. Q. 1 ~ 100을 아래와 같이 출력하세요.

```
[[  1   2   3   4   5   6   7   8   9  10]
 [ 20  19  18  17  16  15  14  13  12  11]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 40  39  38  37  36  35  34  33  32  31]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 60  59  58  57  56  55  54  53  52  51]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 80  79  78  77  76  75  74  73  72  71]
 [ 81  82  83  84  85  86  87  88  89  90]
 [100  99  98  97  96  95  94  93  92  91]]
 ```

In [ ]:
import numpy as np

numbers = np.arange(1, 101).reshape(10, 10)

for i in range(numbers.shape[0]):
    if i % 2 != 0:
        numbers[i] = numbers[i][::-1]

print(numbers)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 20  19  18  17  16  15  14  13  12  11]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 40  39  38  37  36  35  34  33  32  31]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 60  59  58  57  56  55  54  53  52  51]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 80  79  78  77  76  75  74  73  72  71]
 [ 81  82  83  84  85  86  87  88  89  90]
 [100  99  98  97  96  95  94  93  92  91]]


Q17. np.ones((5,5))을 아래와 같이 출력하세요.
```
[[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]]
```

In [ ]:
import numpy as np

array = np.zeros((9, 9))

array[2:7, 2:7] = np.ones((5, 5))

print(array)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


Q18. np.arange(4)을 이용해서 아래와 같이 출력하세요.
```
[[0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0],
 [0, 2, 0, 0, 0],
 [0, 0, 3, 0, 0],
 [0, 0, 0, 4, 0]]
```

In [ ]:
import numpy as np

matrix = np.zeros((5, 5), dtype=int)

for i in range(4):
    matrix[i+1, i] = i + 1

print(matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


Q19. Q. np.zeros((8,8))을 이용해서 아래와 같이 출력하세요(두가지 방식:인덱싱, tile 함수)
```
[[0, 1, 0, 1, 0, 1, 0, 1],
[1, 0, 1, 0, 1, 0, 1, 0],
[0, 1, 0, 1, 0, 1, 0, 1],
[1, 0, 1, 0, 1, 0, 1, 0],
[0, 1, 0, 1, 0, 1, 0, 1],
[1, 0, 1, 0, 1, 0, 1, 0],
[0, 1, 0, 1, 0, 1, 0, 1],
[1, 0, 1, 0, 1, 0, 1, 0]]
```

In [ ]:
import numpy as np

board = np.zeros((8, 8), dtype=int)

board[1::2, ::2] = 1
board[::2, 1::2] = 1

print(board)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Q20. np.arange(336).reshape(6,7,8)에서 100번째 요소의 인덱스를 구하세요.

In [ ]:
import numpy as np

arr = np.arange(336).reshape(6, 7, 8)

index = np.unravel_index(100, arr.shape)

print(index)

(1, 5, 4)
