<a href="https://colab.research.google.com/github/windyday0622/windyday/blob/main/m3_%EB%B6%84%EC%84%9D%20%EB%9D%BC%EC%9D%B4%EB%B8%8C%EB%9F%AC%EB%A6%AC/%20pandas_2_%EC%97%B0%EC%82%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Contetnts
- 기초 연산
- 그룹 연산 : 집계, 변환, 필터링, 그룹매핑
- 함수 매핑 : map, apply, applymap
- Pivot

In [1]:
import pandas as pd

# Correcting the syntax to use dictionaries for key-value pairs
st1 = pd.Series({'국어': 100, '영어': 80, '수학': 90})
st2 = pd.Series({'수학': 80, '국어': 90, '영어': 80})

print(st1,'\n')
print(st2)

국어    100
영어     80
수학     90
dtype: int64 

수학    80
국어    90
영어    80
dtype: int64


In [2]:
pd.DataFrame(st1+st2)

0
국어  190
수학  170
영어  160

In [3]:
# 두 학생의 과목별 점수로 사칙연산 수행
add = st1 + st2
sub = st1 - st2
mul = st1 * st2
div = round((st1 / st2),2)
df = pd.concat([add,sub,mul,div],axis=1)
print(df)

      0   1     2     3
국어  190  10  9000  1.11
수학  170  10  7200  1.12
영어  160   0  6400  1.00


In [4]:
df = pd.concat([add,sub,mul,div], axis=1)
df.columns = ['덧셈', '뺄셈', '곱셈', '나눗셈']
df

덧셈  뺄셈    곱셈   나눗셈
국어  190  10  9000  1.11
수학  170  10  7200  1.12
영어  160   0  6400  1.00

In [5]:
print(add, type(add))

국어    190
수학    170
영어    160
dtype: int64 <class 'pandas.core.series.Series'>


In [6]:
result = pd.DataFrame([add,sub,mul,div])
result

국어       수학      영어
0   190.00   170.00   160.0
1    10.00    10.00     0.0
2  9000.00  7200.00  6400.0
3     1.11     1.12     1.0

In [7]:
result = pd.DataFrame([add,sub,mul,div], index=['덧셈', '뺄셈', '곱셈', '나눗셈'])
result

국어       수학      영어
덧셈    190.00   170.00   160.0
뺄셈     10.00    10.00     0.0
곱셈   9000.00  7200.00  6400.0
나눗셈     1.11     1.12     1.0

In [8]:
import pandas as pd
import numpy as np  # Import NumPy

# Define two pandas Series objects
st1 = pd.Series({'국어': np.nan, '영어': 80, '수학': 90})
st2 = pd.Series({'수학': 80, '국어': 90})

# Perform arithmetic operations
add = st1 + st2  # Addition
sub = st1 - st2  # Subtraction
mul = st1 * st2  # Multiplication
div = round((st1 / st2), 2)  # Division

# Store the results in a DataFrame
result = pd.DataFrame([add, sub, mul, div],
                      index=['덧셈', '뺄셈', '곱셈', '나눗셈'])
result

국어       수학  영어
덧셈  NaN   170.00 NaN
뺄셈  NaN    10.00 NaN
곱셈  NaN  7200.00 NaN
나눗셈 NaN     1.12 NaN

In [9]:
#Q. NULL 값을 0으로 변경하여 결과를 출력하세요.
import pandas as pd
import numpy as np

st1 = pd.Series({'국어': np.nan, '영어': 80, '수학': 90})
st2 = pd.Series({'수학': 80, '국어': 90})

st1 = st1.fillna(0)
st2 = st2.fillna(0)

print("st1:", st1)
print("st2:", st2)

st1: 국어     0.0
영어    80.0
수학    90.0
dtype: float64
st2: 수학    80
국어    90
dtype: int64


In [10]:
df1 = pd.DataFrame(np.arange(12.).reshape((3,4)), columns=list('abcd'))
print(df1,'\n')
df2 = pd.DataFrame(np.arange(20.).reshape((4,5)), columns=list('abcde'))
print(df2)

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0 

      a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0


In [11]:
df2.loc[1,'b'] = np.nan
print(df1)
print(df2)

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0
      a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0


In [12]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [13]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [14]:
# 계산 인자를 뒤집어 계싼
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [15]:
print(df1)
df1.rsub(1)

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0


a    b    c     d
0  1.0  0.0 -1.0  -2.0
1 -3.0 -4.0 -5.0  -6.0
2 -7.0 -8.0 -9.0 -10.0

In [16]:
print(df1)
df1.radd(1)

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0


a     b     c     d
0  1.0   2.0   3.0   4.0
1  5.0   6.0   7.0   8.0
2  9.0  10.0  11.0  12.0

In [17]:
print(df1)
df1.rmul(10)

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0


a     b      c      d
0   0.0  10.0   20.0   30.0
1  40.0  50.0   60.0   70.0
2  80.0  90.0  100.0  110.0

In [18]:
# 배열의 연산
arr = np.arange(12).reshape(3, 4)
print(arr,'\n')
print(arr[0])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[0 1 2 3]


In [19]:
# broadcasting
arr - arr[0]

array([[0, 0, 0, 0],
       [4, 4, 4, 4],
       [8, 8, 8, 8]])

In [20]:
# DataFrame과 Series간 연산
frame = pd.DataFrame(np.arange(12.).reshape(4,3),columns=list('bde'),
                    index = ['Utah','Ohio','Texas','Oregon'])
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [21]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [22]:
series = frame.iloc[0]
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [23]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [24]:
a = np.arange(6).reshape(1,6)
a

array([[0, 1, 2, 3, 4, 5]])

In [25]:
a = np.arange(6).reshape(6,) # 이것은 튜플
a

array([0, 1, 2, 3, 4, 5])

#### 그룹 연산
* 복잡한 데이터를 어떤 기준에 따라 여러 그룹으로 나누어서 관찰할 수 있으며 이런 방식으로 분할 처리하는 것을 그룹 연산이라 함
* 그룹 연산은 데이터를 집계, 변환, 필터링하는데 효율적이며 판다스 groupby() 메소드를 사용함
* 그룹 객체 만들기(분할)
* 그룹 연산 메소드(적용-결합)

In [26]:
import pandas as pd
import seaborn as sns

# titanic 데이터 셋에서 age, sex 등 열을 선택하여 데이터 프레임 만들기
titanic = sns.load_dataset('titanic')
df = titanic.loc[:, ['age', 'sex', 'class', 'fare', 'survived']]

print('승객 수:', len(df))
print(df.head())

승객 수: 891
    age     sex  class     fare  survived
0  22.0    male  Third   7.2500         0
1  38.0  female  First  71.2833         1
2  26.0  female  Third   7.9250         1
3  35.0  female  First  53.1000         1
4  35.0    male  Third   8.0500         0


In [27]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


In [28]:
# class 열을 기준으로 분할(1개 열을 기준)
df1 = df[['age', 'fare', 'survived', 'class']]
grouped = df1.groupby(['class'])
print(grouped)

In [29]:
for key, group in grouped:
  print('*key:', key)
  print('*number:', len(group))
  print(group.head())

*key: ('First',)
*number: 216
     age     fare  survived  class
1   38.0  71.2833         1  First
3   35.0  53.1000         1  First
6   54.0  51.8625         0  First
11  58.0  26.5500         1  First
23  28.0  35.5000         1  First
*key: ('Second',)
*number: 184
     age     fare  survived   class
9   14.0  30.0708         1  Second
15  55.0  16.0000         1  Second
17   NaN  13.0000         1  Second
20  35.0  26.0000         0  Second
21  34.0  13.0000         1  Second
*key: ('Third',)
*number: 491
    age     fare  survived  class
0  22.0   7.2500         0  Third
2  26.0   7.9250         1  Third
4  35.0   8.0500         0  Third
5   NaN   8.4583         0  Third
7   2.0  21.0750         0  Third


In [30]:
# 연산 메소드 적용
average=grouped.mean()
print(average)

              age       fare  survived
class                                 
First   38.233441  84.154687  0.629630
Second  29.877630  20.662183  0.472826
Third   25.140620  13.675550  0.242363


In [31]:
stat = grouped.max()
stat

age      fare  survived
class                           
First   80.0  512.3292         1
Second  70.0   73.5000         1
Third   74.0   69.5500         1

In [32]:
# 개별 그룹 선택하기
group3 = grouped.get_group('Third')

print(group3.head())

    age     fare  survived  class
0  22.0   7.2500         0  Third
2  26.0   7.9250         1  Third
4  35.0   8.0500         0  Third
5   NaN   8.4583         0  Third
7   2.0  21.0750         0  Third


In [33]:
# class 열, sex 열을 기준으로 분할(여러 열을 기준으로 분할)
df2 = df[['age', 'fare', 'survived', 'class', 'sex']]
grouped_two = df2.groupby(['class', 'sex'])

In [34]:
# grouped_two 그룹 객체를 iteration으로 출력
for key, group in grouped_two:
  print('* key:', key)
  print('* number:', len(group))
  print(group.head())

* key: ('First', 'female')
* number: 94
     age      fare  survived  class     sex
1   38.0   71.2833         1  First  female
3   35.0   53.1000         1  First  female
11  58.0   26.5500         1  First  female
31   NaN  146.5208         1  First  female
52  49.0   76.7292         1  First  female
* key: ('First', 'male')
* number: 122
     age      fare  survived  class   sex
6   54.0   51.8625         0  First  male
23  28.0   35.5000         1  First  male
27  19.0  263.0000         0  First  male
30  40.0   27.7208         0  First  male
34  28.0   82.1708         0  First  male
* key: ('Second', 'female')
* number: 76
     age     fare  survived   class     sex
9   14.0  30.0708         1  Second  female
15  55.0  16.0000         1  Second  female
41  27.0  21.0000         0  Second  female
43   3.0  41.5792         1  Second  female
53  29.0  26.0000         1  Second  female
* key: ('Second', 'male')
* number: 108
     age  fare  survived   class   sex
17   NaN  13.0       

In [35]:
# grouped_two 그룹 객체에 연산 메소드 적용
average_two = grouped_two.mean()
print(average_two)

                     age        fare  survived
class  sex                                    
First  female  34.611765  106.125798  0.968085
       male    41.281386   67.226127  0.368852
Second female  28.722973   21.970121  0.921053
       male    30.740707   19.741782  0.157407
Third  female  21.750000   16.118810  0.500000
       male    26.507589   12.661633  0.135447


In [36]:
print(type(average_two))

# grouped_two 그룹 객체에서 개별 그룹 선택하기
group3f = grouped_two.get_group(('Third', 'female'))
print(group3f.head())

<class 'pandas.core.frame.DataFrame'>
     age     fare  survived  class     sex
2   26.0   7.9250         1  Third  female
8   27.0  11.1333         1  Third  female
10   4.0  16.7000         1  Third  female
14  14.0   7.8542         0  Third  female
18  31.0  18.0000         0  Third  female


데이터 집계(agg),
- 집계 연산을 처리하는 사용자 정의 함수를 그룹 객체에 적용하려면 agg() 메서드 사용
- 모든열에 여러 함수를 매핑 : group객체.agg([함수1,함수2,함수3,…])
- 각 열마다 다른 함수를 매핑 : group객체.agg({‘열1’: 함수1, ‘열2’:함수2, …})

변환(transform)
- 원소의 본래 행 인덱스와 열 이름을 기준으로 연산 결과를 반환
- 데이터 변환 연산 : group객체.transform(매핑함수)

필터링(filter)
- 그룹 객체에 filter() 메서드를 적용할 때 조건식을 가진 함수를 전달하면 조건이 참인 그룹만을 남김
- 그룹 객체 필터링 : group 객체.filter(조건 함수식)

객체에 함수 매핑(apply)
 - 판다스 객체의 개별 원소를 특정 함수에 일대일로 매핑. 사용자가 원하는 대부분의 연산을 그룹 객체에 적용
 - group 객체.apply(매핑함수)

In [37]:
import pandas as pd
import seaborn as sns

# titanic 데이터셋에서 age, sex 등 5개 열을 선택하여 데이터프레임 만들기
titanic = sns.load_dataset('titanic')
df = titanic.loc[:, ['age','class', 'fare', 'survived']]

# class 열을 기준으로 분할
grouped = df.groupby(['class'])

In [38]:
mean_all = grouped.mean()
print(mean_all)
print()
print(type(mean_all))

              age       fare  survived
class                                 
First   38.233441  84.154687  0.629630
Second  29.877630  20.662183  0.472826
Third   25.140620  13.675550  0.242363

<class 'pandas.core.frame.DataFrame'>


In [39]:
mean_all.index.name =None
mean_all

age       fare  survived
First   38.233441  84.154687  0.629630
Second  29.877630  20.662183  0.472826
Third   25.140620  13.675550  0.242363

In [40]:
# 각 그룹에 대한 모든 열의 표준편차를 집계하여 데이터프레임으로 반환
std_all =grouped.std()
print(std_all)
print()
print(type(std_all))

              age       fare  survived
First   14.802856  78.380373  0.484026
Second  14.001077  13.417399  0.500623
Third   12.495398  11.778142  0.428949

<class 'pandas.core.frame.DataFrame'>


In [41]:
# 각 그룹에 대한 fare 열의 표준편차를 집계하여 시리즈로 반환
std_fare = grouped.fare.std()
print(std_fare)
print()
print(type(std_fare))

First     78.380373
Second    13.417399
Third     11.778142
Name: fare, dtype: float64

<class 'pandas.core.series.Series'>


In [42]:
# 그룹 객체에 agg() 메소드 적용 -사용자 정의 함수를 인수로 전달
def min_max(x):   #최대값 - 최소값
    return x.max() - x.min()

# 각 그룹의 최대값과 최소값의 차이를 계싼하여 그룹별로 집계
agg_minmax = grouped.agg(min_max)
print(agg_minmax.head())

          age      fare  survived
First   79.08  512.3292         1
Second  69.33   73.5000         1
Third   73.58   69.5500         1


In [43]:
# 모든 열에 여러 함수를 매핑 : group객체.agg([함수1, 함수2, 함수3,...])
# 각 열마다 다른 함수를 매핑 : group객체.agg({'열1' : 함수1, '열2' : 함수2, ...})

agg_all =grouped.agg(['min', 'max'])
print(agg_all.head())

         age       fare           survived    
         min   max  min       max      min max
First   0.92  80.0  0.0  512.3292        0   1
Second  0.67  70.0  0.0   73.5000        0   1
Third   0.42  74.0  0.0   69.5500        0   1


In [44]:
# 각 열마다 다른 함수를 적용하여 집계
agg_sep =grouped.agg({'fare':['min', 'max'], 'age':'mean'})
print(agg_sep.head())

       fare                  age
        min       max       mean
First   0.0  512.3292  38.233441
Second  0.0   73.5000  29.877630
Third   0.0   69.5500  25.140620


In [45]:
import pandas as pd
import seaborn as sns

# titanic 데이터셋에서 age, sex 등 5개 열을 선택하여 데이터프레임 만들기
titanic = sns.load_dataset('titanic')
df = titanic.loc[:, ['age','class', 'fare', 'survived']]

# class 열을 기준으로 분할
grouped = df.groupby(['class'])

In [46]:
# 데이터 개수가 200개 이상인 그룹만을 필터링하여 데이터프레임으로 반환
grouped_filter =grouped.filter(lambda x: len(x)>= 200)
print(grouped_filter.head())
print()
print(type(grouped_filter))

    age  class     fare  survived
0  22.0  Third   7.2500         0
1  38.0  First  71.2833         1
2  26.0  Third   7.9250         1
3  35.0  First  53.1000         1
4  35.0  Third   8.0500         0

<class 'pandas.core.frame.DataFrame'>


In [47]:
grouped_filter.value_counts('class')

class
Third     491
First     216
Second      0
Name: count, dtype: int64

#### 함수 매핑
커스텀 함수(custom function)를 DataFrame에 적용하려면 map함수, apply함수, applymap함수를 사용
- map 함수는 Series의 각 요소에 함수를 적용.
- apply 함수는 Series 또는 DataFrame의 행이나 열에 함수를 적용.
- applymap 함수는 DataFrame의 각 요소에 함수를 적용.

In [48]:
import pandas as pd

s = pd.Series([1, 2, 3,  4, 5])

s_mapped = s.map(lambda x: x+ 2)
print(s_mapped)

0    3
1    4
2    5
3    6
4    7
dtype: int64


In [49]:
df = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [4, 5, 6],
    'C': [7, 8, 9]
})

# 각 열에 대해 최대값을 구하는 함수
df_applied_col = df.apply(lambda x: x.max(), axis=0)  # Corrected the syntax
print(df_applied_col)

# 각 행에 대해 합계를 구하는 함수
df_applied_row = df.apply(lambda x: x.sum(), axis=1)  # Corrected the syntax
print(df_applied_row)

A    3
B    6
C    9
dtype: int64
0    12
1    15
2    18
dtype: int64


In [50]:
# applymap 함수는 DataFrame에만 적용되며, 각 요소에 함수를 적용

df = pd.DataFrame({
    'A':[1, 2, 3],
    'B':[4, 5, 6],
    'C':[7, 8, 9]
})

# 각 요소에 2를 더하는 함수
df_applymapped = df.applymap(lambda x: x + 2)
print(df_applymapped)

   A  B   C
0  3  6   9
1  4  7  10
2  5  8  11


In [51]:
# 함수 적용과 매핑
import numpy as np
np.random.seed(10)
frame = pd.DataFrame(np.random.randn(4,3),columns=list('bde'),
                    index = ['Utah','Ohio','Texas','Oregon'])
frame

b         d         e
Utah    1.331587  0.715279 -1.545400
Ohio   -0.008384  0.621336 -0.720086
Texas   0.265512  0.108549  0.004291
Oregon -0.174600  0.433026  1.203037

In [52]:
format = lambda x: '%.2f' %x

In [53]:
# map 함수는 series에만 적용
frame['e'].map(format)

Utah      -1.55
Ohio      -0.72
Texas      0.00
Oregon     1.20
Name: e, dtype: object

In [54]:
f1 = lambda x: round(x*10)
frame.apply(f1,axis=0)

b    d     e
Utah    13.0  7.0 -15.0
Ohio    -0.0  6.0  -7.0
Texas    3.0  1.0   0.0
Oregon  -2.0  4.0  12.0

In [55]:
frame

b         d         e
Utah    1.331587  0.715279 -1.545400
Ohio   -0.008384  0.621336 -0.720086
Texas   0.265512  0.108549  0.004291
Oregon -0.174600  0.433026  1.203037

In [56]:
f1 = lambda x: round(x*20)
frame.apply(f1,axis=1)

b     d     e
Utah    27.0  14.0 -31.0
Ohio    -0.0  12.0 -14.0
Texas    5.0   2.0   0.0
Oregon  -3.0   9.0  24.0

In [57]:
f1 = lambda x: sum(x)
frame.apply(f1,axis=0)

b    1.414114
d    1.878190
e   -1.058157
dtype: float64

In [58]:
# 여러 값을 가진 Series 반환
print(frame,'\n')
def f(x):
      return pd.Series([x.min(),x.max()], index=['min','max'])
frame.apply(f)

               b         d         e
Utah    1.331587  0.715279 -1.545400
Ohio   -0.008384  0.621336 -0.720086
Texas   0.265512  0.108549  0.004291
Oregon -0.174600  0.433026  1.203037 



b         d         e
min -0.174600  0.108549 -1.545400
max  1.331587  0.715279  1.203037

In [59]:
# 실수값을 문자열 포맷으로 변환
format = lambda x: '%.2f' %x
frame.applymap(format)

b     d      e
Utah     1.33  0.72  -1.55
Ohio    -0.01  0.62  -0.72
Texas    0.27  0.11   0.00
Oregon  -0.17  0.43   1.20

In [60]:
data = np.random.randint(1,100,size=(5,5))
df = pd.DataFrame(data, columns=list('abcde'))
df

a   b   c   d   e
0  73  79  50  52  55
1  78  70  14  26  14
2  93  87  31  31  90
3  13  66  32  58  37
4  28  19  94  78  23

In [61]:
df['f'] = df.apply(lambda x:x.a+x.b+x.c+x.d+x.e,axis=1)
df

a   b   c   d   e    f
0  73  79  50  52  55  309
1  78  70  14  26  14  202
2  93  87  31  31  90  332
3  13  66  32  58  37  206
4  28  19  94  78  23  242

In [62]:
# 표준화 : 데이터 평균을 0, 표준편차를 1로 변환하는 과정. 이과정을 통해 데이터의 스케일을 조정하고 비교 가능한 형태로 만듬.
def z_score(x):
    return (x -x.mean()) / x.std()

In [63]:
# 원소의 본래 행 인덱스와 열 이름을 기준으로 연산 결과를 반환
df_zscore = df.a.transform(z_score)
df_zscore

0    0.463330
1    0.608121
2    1.042493
3   -1.274159
4   -0.839786
Name: a, dtype: float64

In [64]:
df_zscore = df.apply(lambda x:z_score(x))
df_zscore

a         b         c         d         e         f
0  0.463330  0.557519  0.189458  0.142054  0.371951  0.853426
1  0.608121  0.218487 -0.986486 -1.089082 -0.989656 -0.944145
2  1.042493  0.858880 -0.431179 -0.852325  1.534300  1.239820
3 -1.274159  0.067806 -0.398514  0.426162 -0.225828 -0.876946
4 -0.839786 -1.702693  1.626721  1.373190 -0.690767 -0.272156

apply vs map
- apply는 DataFrame의 행이나 열 단위로 함수를 적용할 수 있지만, map은 Series의 각 요소에만 함수를 적용
- Series의 각 요소를 변환하는 간단한 작업에는 map이 적합하고, 더 복잡한 변환이 필요한 경우나 DataFrame 전체를 다룰 때는 apply가 유용

apply vs applymap
- df.apply는 DataFrame의 각 행(row) 또는 열(column)에 함수를 적용합니다. 기본적으로 axis=0으로 설정되어 있어 열 단위로 함수를 적용
- 각 행 또는 열 자체가 Series로 전달되며, 이 Series 전체에 대해 함수를 적용하려고 한다.
- applymap은 DataFrame의 모든 요소에 대해 함수를 적용하므로, 전체 DataFrame에 대한 변환이 필요할 때 유용

####Pivot
pivot 함수의 구성 형식
- index: 새로운 DataFrame에서 인덱스로 사용할 기존 열 또는 열들의 이름.
- columns: 새로운 DataFrame에서 열로 사용할 기존 열 또는 열들의 이름.
- values: 피벗할 때 사용할 값이 있는 열의 이름.

기능
- 긴 형식의 데이터를 넓은 형식으로 변환하여 특정 차원에서 데이터를 재구성.
- 피벗된 데이터를 통해 시간 경과에 따른 변화나 여러 카테고리의 비교를 쉽게 할 수 있다.
- 넓은 형식의 데이터는 시각화 도구에서 더 쉽게 다룰 수 있다.

In [67]:
# 날짜를 인덱스로, 도시를 열로, 온도를 값으로 사용하여 피벗 테이블을 생성
import pandas as pd

data = {
    'date': ['2021-01-01', '2021-01-01', '2021-01-02', '2021-01-02'],
    'city': ['New York', 'Los Angeles', 'New York', 'Los Angeles'],
    'temperature': [32, 75, 30, 78]
}
df=pd.DataFrame(data)
print(df,'\m')
pivot_df = df.pivot(index='date', columns='city', values='temperature')
print(pivot_df)

         date         city  temperature
0  2021-01-01     New York           32
1  2021-01-01  Los Angeles           75
2  2021-01-02     New York           30
3  2021-01-02  Los Angeles           78 \m
city        Los Angeles  New York
date                             
2021-01-01           75        32
2021-01-02           78        30


In [68]:
# 중복된 값을 평균으로 처리하여 피벗 테이블을 형성
data = {
    'date': ['2021-01-01','2021-01-01', '2021-01-01', '2021-01-02', '2021-01-02'],
    'city': ['New York', 'Los Angeles', 'New York', 'New York' ,'Los Angeles'],
    'temperature': [32, 75, 30, 30, 78]
}
df=pd.DataFrame(data)

pivot_table_df = df.pivot_table(index='date', columns='city', values='temperature', aggfunc='mean')
print(pivot_table_df)

city        Los Angeles  New York
date                             
2021-01-01           75        31
2021-01-02           78        30


In [70]:
# 다중인덱스와 다중 값 사용: 날짜와 도시를 기준으로 온도와 습도를 모두 포함한 피벗 테이블을 생성
data = {
    'date': ['2021-01-01', '2021-01-01', '2021-01-02', '2021-01-02'],
    'city': ['New York', 'Los Angeles', 'New York', 'Los Angeles'],
    'temperature': [32, 75, 30, 78],
    'humidity': [80, 20, 85, 15]
}
df=pd.DataFrame(data)
print(df,'\n')
pivot_multi_df = df.pivot(index='date', columns='city')
print(pivot_multi_df)

         date         city  temperature  humidity
0  2021-01-01     New York           32        80
1  2021-01-01  Los Angeles           75        20
2  2021-01-02     New York           30        85
3  2021-01-02  Los Angeles           78        15 

           temperature             humidity         
city       Los Angeles New York Los Angeles New York
date                                                
2021-01-01          75       32          20       80
2021-01-02          78       30          15       85


In [71]:
# Q. 주어진 매출 데이터에서 각 연도와 각 제품별로 총 매출액을 계산하세요.

data = {
    'Year': [2020, 2020, 2021, 2021, 2022, 2022, 2022, 2023, 2023],
    'Product': ['A', 'B', 'A', 'B', 'A', 'B', 'C', 'A', 'C'],
    'Sales': [100, 150, 200, 250, 300, 350, 400, 500, 450]
}

df=pd.DataFrame(data)
print(df,'\n')

total_sales = df.groupby(['Year', 'Product'])['Sales'].sum().reset_index()
print(total_sales)

   Year Product  Sales
0  2020       A    100
1  2020       B    150
2  2021       A    200
3  2021       B    250
4  2022       A    300
5  2022       B    350
6  2022       C    400
7  2023       A    500
8  2023       C    450 

   Year Product  Sales
0  2020       A    100
1  2020       B    150
2  2021       A    200
3  2021       B    250
4  2022       A    300
5  2022       B    350
6  2022       C    400
7  2023       A    500
8  2023       C    450


In [75]:
# Q. 주어진 직원 근무시간 데이터에서, 각 직원별로 각 월의 총 근무 시간을 계산하세요.

data = {
    'Employee': ['John', 'John', 'John', 'Anna', 'Anna', 'Anna', 'Peter', 'Peter', 'Peter'],
    'Month': ['Jan', 'Feb', 'Mar', 'Jan', 'Feb', 'Mar', 'Jan', 'Feb', 'Mar'],
    'Hours': [160, 170, 175, 150, 165, 180, 155, 160, 170]
}

df = pd.DataFrame(data)
print(df,'\n')

pivot_table = df.pivot(index='Employee', columns='Month', values='Hours')
print(pivot_table)

  Employee Month  Hours
0     John   Jan    160
1     John   Feb    170
2     John   Mar    175
3     Anna   Jan    150
4     Anna   Feb    165
5     Anna   Mar    180
6    Peter   Jan    155
7    Peter   Feb    160
8    Peter   Mar    170 

Month     Feb  Jan  Mar
Employee               
Anna      165  150  180
John      170  160  175
Peter     160  155  170
