<a href="https://colab.research.google.com/github/windyday0622/windyday/blob/main/m3_%EB%B6%84%EC%84%9D%20%EB%9D%BC%EC%9D%B4%EB%B8%8C%EB%9F%AC%EB%A6%AC/%20pandas_1_%EB%8D%B0%EC%9D%B4%ED%84%B0_%EA%B5%AC%EC%A1%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Contents
 - 데이터 구조 Series, DataFrame
 - 인덱스, 생성, 선택, 추가, 변경, 삭제, 전치
 - 파이썬 자료형과 양방향 변환

#### 판다스
Pandas는 파이썬에서 데이터 분석 및 조작을 위한 강력하고 유연한 오픈 소스 라이브러리. Series와 DataFrame 같은 고수준의 데이터 구조를 제공하여, 복잡한 데이터 조작을 직관적이고 효율적으로 수행할 수 있게 한다.

[Pandas의 주요 역할과 기능]

* DataFrame과 Series: 2차원 테이블과 1차원 배열 형태의 데이터 구조를 제공
* 데이터 처리: 결측값 처리, 데이터 정제, 필터링, 병합, 연결 및 변환 등을 위한 다양한 기능을 제공
* 데이터 분석: 기술통계, 그룹화, 시계열 분석 등 복잡한 분석 작업을 제공
* 입출력 기능: CSV, Excel, SQL, JSON 등 다양한 파일 형식의 데이터를 읽고 쓸 수 있는 기능을 제공
* 시각화 지원: 매트플롯립과 연동하여 데이터 시각화가 가능하도록 제공
* 라이브러리는 여러 종류의 class와 다양한 내장 함수로 구성. 시리즈와 데이터프레임은 대표적인 클래스 객체임
* 시리즈 인덱스는 데이터 값과 일대일 대응. 파이썬 딕셔너리와 비슷한 구조. pandas.Series(딕셔너리)

In [2]:
# 시리즈 클래스 만들기
# pandas 불러오기
import pandas as pd

#k:v 구조를 갖는 딕셔너리를 만들고 변수 dict_data에 저장
dict_data = {'a':1, 'b':2, 'c':3}

sr = pd.Series(dict_data)
print(sr)
type(sr)

a    1
b    2
c    3
dtype: int64


pandas.core.series.Series

In [6]:
#리스트를 시리즈로 변환

list_data = ['2019-07-02',3.14, 'ABC', 100, True]
sr = pd.Series(list_data)
print(sr, type(sr))

0    2019-07-02
1          3.14
2           ABC
3           100
4          True
dtype: object <class 'pandas.core.series.Series'>


In [7]:
#인덱스 및 값
idx = sr.index
val = sr.values
print(idx)
print(val)

RangeIndex(start=0, stop=5, step=1)
['2019-07-02' 3.14 'ABC' 100 True]


In [8]:
#튜플을 시리즈로 변환
tup_data = ('kevin', '2019-07-02', '남', True)
sr= pd.Series(tup_data)
sr = pd.Series(tup_data, index = ['이름', '생년월일', '성별', '학생여부'])
print(sr)

이름           kevin
생년월일    2019-07-02
성별               남
학생여부          True
dtype: object


In [9]:
# 인덱싱
import warnings
warnings.filterwarnings('ignore')
print(sr[0])
print(sr['이름'])
print(sr[[1, 2]])

kevin
kevin
생년월일    2019-07-02
성별               남
dtype: object


In [10]:
#배열
import numpy as np

s1 = np.arange(11, 21, 2)
print(s1, type(s1))
print()
s2 = pd.Series(s1, index=list('abcde'))
print(s2, type(s2))

[11 13 15 17 19] <class 'numpy.ndarray'>

a    11
b    13
c    15
d    17
e    19
dtype: int64 <class 'pandas.core.series.Series'>


Q. 배열을 생성 후 시리즈로 변환하여 아래와 같이 출력하세요:
data = np.arange(1000, 5000, 1000)
state = ['Califonia','Ohio','Oregon','Texas']

In [ ]:
state
Califonia  1000
Ohaio      2000
Oregon     3000
Texas      4000
Name: population, dtype: int32

In [11]:
import numpy as np
data = np.arange(1000, 5000, 1000)
state = ['Califonia', 'Ohio', 'Orehon', 'Texas']
obj = pd.Series(data,index=state)
obj

Califonia    1000
Ohio         2000
Orehon       3000
Texas        4000
dtype: int64

In [12]:
print(s2, type(s2))

a    11
b    13
c    15
d    17
e    19
dtype: int64 <class 'pandas.core.series.Series'>


In [13]:
list_form_series = s2.tolist()
list_form_series

[11, 13, 15, 17, 19]

In [15]:
df_form_series = s2.to_frame(name='Value')
df_form_series

Value
a     11
b     13
c     15
d     17
e     19

In [16]:
df_form_series = s2.to_dict()
df_form_series

{'a': 11, 'b': 13, 'c': 15, 'd': 17, 'e': 19}

Q. 아래 시리즈에서 null값을 2개 입력 후 그 값을 0으로 대체 후 null값 여부를 확인한 후 출력하세요.


In [ ]:
import pandas as pd
import numpy as np

# 1. Series 생성
s = pd.Series([5, 15, 25, 35, 45], index=['x', 'y', 'z', 'w', 'v'])

In [21]:
import pandas as pd
import numpy as np

s = pd.Series([5, 15, 25, 35, 45], index=['x', 'y', 'z', 'w', 'v'])

s['x'] = np.nan
s['z'] = np.nan

s = s.fillna(0)

null_check = s.isnull()

print(s)
print(null_check)

x     0.0
y    15.0
z     0.0
w    35.0
v    45.0
dtype: float64
x    False
y    False
z    False
w    False
v    False
dtype: bool


Q. 주어진 리스트 [1, 2, 3, 4, 5]를 Pandas Series로 변환하고, 각 원소에 10을 더한 Series를 출력하세요.

In [ ]:
import pandas as pd

# 주어진 리스트
data_list = [1, 2, 3, 4, 5]

In [23]:
import pandas as pd

data_list = [1, 2, 3, 4, 5]
data_series = pd.Series(data_list)

result_series = data_series + 10

print(result_series)

0    11
1    12
2    13
3    14
4    15
dtype: int64


Q. Series [10, 20, 30, 40, 50]를 생성하고 인덱스를 ['a', 'b', 'c', 'd', 'e']로 설정하세요. 인덱스를 기준으로 Series를 정렬한 결과를 출력하세요.

In [24]:
import pandas as pd

data = [10, 20, 30, 40, 50]
index = ['a', 'b', 'c', 'd', 'e']
series = pd.Series(data, index=index)

sorted_series = series.sort_index()

print(sorted_series)

a    10
b    20
c    30
d    40
e    50
dtype: int64


Q. Series ['a':1, 'b':2, 'c':3, 'd':4, 'e':5]에서 인덱스 'b', 'd'에 해당하는 원소를 선택하여 출력하세요.

In [ ]:
import pandas as pd

# 주어진 데이터와 인덱스
data = [1, 2, 3, 4, 5]
index = ['a', 'b', 'c', 'd', 'e']

In [25]:
import pandas as pd

data = [1, 2, 3, 4, 5]
index = ['a', 'b', 'c', 'd', 'e']
series = pd.Series(data, index=index)

selected_elements = series[['b', 'd']]

print(selected_elements)

b    2
d    4
dtype: int64


#### 데이터프레임
* 데이터프레임은 2차원 배열. R의 데이터프레임에서 유래.
* 데이터프레임의 열은 각각 시리즈 개체.
* 시리즈를 열벡터라고 하면 데이터프레임은 여러개의 열벡터들이 같은 행 인덱스를
  기준으로 줄지어 결합된 2차원 벡터 또는 행렬.
* 선형대수학에서 열 벡터(m x 1 행렬)는 m 원소들의 단일 열 행렬
* 행 벡터(1 x m 행렬)은 m원소들의 단일 행 행렬.
* 리스트, 딕셔너리, ndarray 등 다양한 데이터로부터 생성
* 반대로 리스트, 딕셔너리, ndarray 등으로 변환될 수 있음

In [4]:
# 배열을 데이터프레임으로 변환
import numpy as np
import pandas as pd
np.random.seed(0)
data = np.random.randint(100, 120, size=(3,3))
print(data, type(data))

df = pd.DataFrame(data,index=['d1', 'd2', 'd3'],
                  columns = ['pd', 'sales', 'inv'])

df

[[112 115 100]
 [103 103 107]
 [109 119 118]] <class 'numpy.ndarray'>


pd  sales  inv
d1  112    115  100
d2  103    103  107
d3  109    119  118

In [5]:
print(df.pd, type(df.pd))

d1    112
d2    103
d3    109
Name: pd, dtype: int64 <class 'pandas.core.series.Series'>


In [6]:
df = pd.DataFrame(data, columns = ['pd', 'sales', 'inv'])
df

pd  sales  inv
0  112    115  100
1  103    103  107
2  109    119  118

#### Pandas의 iloc와 loc 메서드
DataFrame과 Series에서 데이터의 특정 위치나 라벨에 접근하기 위한 중요한 도구이며 두 메서드는 각각 고유한 용도를 가지고 있다.

- iloc (Integer Location)
  - 정수 인덱스 기반으로 데이터에 접근하는 메서드. 즉, DataFrame이나 Series의 특정 위치에 있는 데이터를 선택할 때 사용.
  - 슬라이싱 지원: Python 리스트와 유사하게 슬라이싱을 지원.
  - 끝점 포함하지 않음: 슬라이싱 시 끝점은 포함하지 않는다.
- loc (Label Location)
  - 라벨 인덱스 기반으로 데이터에 접근하는 메서드. 즉, DataFrame이나 Series의 라벨 이름을 사용하여 데이터에 접근.
  - 슬라이싱 지원: 라벨을 사용하여 슬라이싱을 지원.
  - 양 끝점 포함: 슬라이싱 시 끝점을 포함.

In [8]:
import pandas as pd

# 데이터 프레임 생성
data = {
    'A': [1, 2, 3, 4],
    'B': [5, 6, 7, 8],
    'C': [9, 10, 11, 12]
}
df = pd.DataFrame(data)
print(df,'\n')
# 첫번쨰 행, 두번째 열의 값 선택
print(df.iloc[0, 1])   # 출력: 5
# 첫번째부터 두번째 행, 첫번째부터 두번째 열 선택
print(df.iloc[0:2, 0:2])

   A  B   C
0  1  5   9
1  2  6  10
2  3  7  11
3  4  8  12 

5
   A  B
0  1  5
1  2  6


In [10]:
#데이터 프레임 생성
data = {
    'A': [1, 2, 3, 4],
    'B': [5, 6, 7, 8],
    'C': [9, 10, 11, 12]
}
df = pd.DataFrame(data, index=['a', 'b', 'c', 'd'])
print(df,'\n')
# 인덱스 'a', 열의 'B'의 값 선택
print(df.loc['a', 'B'])  # 출력 : 5

# 인덱스 'a'부터 'b', 열 'A'부터 'B'
print(df.loc['a':'b', 'A':'B'])

   A  B   C
a  1  5   9
b  2  6  10
c  3  7  11
d  4  8  12 

5
   A  B
a  1  5
b  2  6


In [13]:
df = pd.DataFrame(data,index=['d1', 'd2', 'd3'],
                  columns = ['pd', 'sales', 'inv'])
print(df.iloc[1],'\n')
print(df.loc['d2'])

pd       NaN
sales    NaN
inv      NaN
Name: d2, dtype: object 

pd       NaN
sales    NaN
inv      NaN
Name: d2, dtype: object


In [17]:
print(df.iloc[1,:], '\n')
print(df.loc['d2',:])

pd       NaN
sales    NaN
inv      NaN
Name: d2, dtype: object 

pd       NaN
sales    NaN
inv      NaN
Name: d2, dtype: object


In [18]:
import numpy as np
import pandas as pd
np.random.seed(0)
data = np.random.randint(100, 120, size=(3,3))
print(data, type(data))

df = pd.DataFrame(data,index=['d1', 'd2', 'd3'],
                  columns = ['pd', 'sales', 'inv'])
print(df.iloc[1,2])
print(df.loc['d2', 'inv'])

[[112 115 100]
 [103 103 107]
 [109 119 118]] <class 'numpy.ndarray'>
107
107


In [19]:
df.loc['d3']= 0
df

pd  sales  inv
d1  112    115  100
d2  103    103  107
d3    0      0    0

In [20]:
df.loc['d4']= 0
df

pd  sales  inv
d1  112    115  100
d2  103    103  107
d3    0      0    0
d4    0      0    0

In [24]:
import numpy as np
import pandas as pd
np.random.seed(0)
data = np.random.randint(100, 120, size=(3,3))
print(data, type(data))

df = pd.DataFrame(data,index=['d1', 'd2', 'd3'],
                  columns = ['pd', 'sales', 'inv'])
df.loc[:, 'profit'] = 10
df

[[112 115 100]
 [103 103 107]
 [109 119 118]] <class 'numpy.ndarray'>


pd  sales  inv  profit
d1  112    115  100      10
d2  103    103  107      10
d3  109    119  118      10

[파이썬 random 함수]

In [25]:
import random
print(random.random(),'\n') # 0.0 <= x < 1.0 사이
print(random.randint(1,10),'\n') # 1에서 10사이의 정수중에서 난수 값 리턴
print(random.uniform(10,20), '\n') # min max 사이 float 리턴
print(random.randrange(10), '\n') # 지정 범위 int 리턴
print(random.choice([1,2,3,4,5]),'\n') # 리스트 내부에 있는 요소를 랜덤하게 선택
li = [1,2,3,4,5]
print(random.sample(li,3),'\n') # 리스트 요소를 중복이 안되게 리턴
random.shuffle(li) # 리스트 요소를 다시 섞어서 리턴
print(li)

0.9688348392951813 

6 

15.834879067419305 

7 

2 

[3, 1, 2] 

[2, 5, 1, 4, 3]


[numpy random 함수]

- np.random.seed : seed를 통한 난수 생성
- np.random.randint : 정수 난수 1개 생성
- np.random.rand : 0부터 1사이의 균일분포에서 난수 매트릭스 배열 생성
- np.random.randn : 가우시안 표준 정규분포에서 난수 매트릭스 배열 생성
- np.random.shuffle : 기존의 데이터의 순서 바꾸기
- np.random.choice : 기존 데이터에서 sampling

In [26]:
import numpy as np
print(np.random.randint(6), '\n') # 0 ~ 5까지 정수인 난수 1개
print(np.random.randint(1,20),'\n') # 1 ~ 19까지 정수인 난수 1개
print(np.random.randint(10, size=10), '\n') # 0 ~ 9까지 정수인 난수 10개
print(np.random.randint(10,20, size=10),'\n') # 10 ~ 19까지 정수인 난수 10개
print(np.random.randint(10,20, size=(3,5))) # 10 ~ 19까지 정수인 난수로 3행 5열 배열 생성

4 

7 

[8 8 1 6 7 7 8 1 5 9] 

[18 19 14 13 10 13 15 10 12 13] 

[[18 11 13 13 13]
 [17 10 11 19 19]
 [10 14 17 13 12]]


In [31]:
# id, gender, age, region
import numpy as np
import pandas as pd
id = np.arange(1, 1001)
i1 = pd.Series(id)
gender = np.random.randint(2, size = 1000)
g1 = pd.Series(gender)
age = np.random.randint(1, 101, size = 1000)
a1 = pd.Series(age)
region = np.random.randint(1, 11, size = 1000)
r1 = pd.Series(region)

df = pd.concat([i1, g1, a1, r1], axis=1)
df.rename(columns={0:'id', 1:'gender', 2:'age', 3:'region'}, inplace=True)
df.head()

id  gender  age  region
0   1       0   93       7
1   2       0   70       1
2   3       0    2       5
3   4       0   18       9
4   5       1   63       5

In [34]:
df.drop([0], axis=0, inplace=True)
df.head()

id  gender  age  region
1   2       0   70       1
2   3       0    2       5
3   4       0   18       9
4   5       1   63       5
5   6       1   48      10

- at은 라벨 기반 인덱싱을 사용.단일 값을 접근할 때 loc접근자 보다 빠르다.
- 여러 값을 동시에 접근하려면 loc 접근자를 사용.

In [36]:
df.loc[5, 'id']

6

In [35]:
df.at[5, 'id']

6

In [38]:
df1 = df.drop(df.at[5,'id'])
df.head(7)

id  gender  age  region
1   2       0   70       1
2   3       0    2       5
3   4       0   18       9
4   5       1   63       5
5   6       1   48      10
6   7       1    9       3
7   8       1   74       3

Task1_0527. 4개의 Series를 결합하여 데이터프레임을 생성하여 출력하세요.
- 출력한 데이터프레임에서 추출하고 싶은 5개의 데이터를 인덱싱하여 출력
- null값을 3개 추가
- null값의 개수를 확인하고 삭제
- 2개의 데이터를 수정
- 1개의 행을 삭제

In [39]:
df1 = df.copy()
df1.head()

id  gender  age  region
1   2       0   70       1
2   3       0    2       5
3   4       0   18       9
4   5       1   63       5
5   6       1   48      10

In [43]:
np.random.seed(0)
a =np.random.randint(1,5,size=(10,5))
print(a,type(a))

[[1 4 2 1 4]
 [4 4 4 2 4]
 [2 3 1 4 3]
 [1 1 1 3 2]
 [3 4 4 3 1]
 [2 2 2 2 1]
 [2 1 4 1 4]
 [2 3 4 4 1]
 [3 4 1 2 4]
 [2 4 4 3 4]] <class 'numpy.ndarray'>


In [44]:
#2차원 리스트를 데이터 프레임으로 변환
list1 = a.tolist()

df1 = pd.DataFrame(list1, columns=['c1', 'c2', 'c3', 'c4', 'c5'])
print(df1.head())

   c1  c2  c3  c4  c5
0   1   4   2   1   4
1   4   4   4   2   4
2   2   3   1   4   3
3   1   1   1   3   2
4   3   4   4   3   1


In [47]:
#데이터 프레임을 배열, 리스트, 딕셔너리로 변환
ar = df1.values
print(ar,type(ar))
print()
li = ar.tolist()
print(li, type(li))
print()
dict = df1.to_dict('list')
print(dict, type(dict))

[[1 4 2 1 4]
 [4 4 4 2 4]
 [2 3 1 4 3]
 [1 1 1 3 2]
 [3 4 4 3 1]
 [2 2 2 2 1]
 [2 1 4 1 4]
 [2 3 4 4 1]
 [3 4 1 2 4]
 [2 4 4 3 4]] <class 'numpy.ndarray'>

[[1, 4, 2, 1, 4], [4, 4, 4, 2, 4], [2, 3, 1, 4, 3], [1, 1, 1, 3, 2], [3, 4, 4, 3, 1], [2, 2, 2, 2, 1], [2, 1, 4, 1, 4], [2, 3, 4, 4, 1], [3, 4, 1, 2, 4], [2, 4, 4, 3, 4]] <class 'list'>

{'c1': [1, 4, 2, 1, 3, 2, 2, 2, 3, 2], 'c2': [4, 4, 3, 1, 4, 2, 1, 3, 4, 4], 'c3': [2, 4, 1, 1, 4, 2, 4, 4, 1, 4], 'c4': [1, 2, 4, 3, 3, 2, 1, 4, 2, 3], 'c5': [4, 4, 3, 2, 1, 1, 4, 1, 4, 4]} <class 'dict'>


In [ ]:
# file 생성
