<a href="https://colab.research.google.com/github/windyday0622/windyday/blob/main/m3_%EB%B6%84%EC%84%9D%20%EB%9D%BC%EC%9D%B4%EB%B8%8C%EB%9F%AC%EB%A6%AC/%20pandas_1_%EB%8D%B0%EC%9D%B4%ED%84%B0_%EA%B5%AC%EC%A1%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Contents
 - 데이터 구조 Series, DataFrame
 - 인덱스, 생성, 선택, 추가, 변경, 삭제, 전치
 - 파이썬 자료형과 양방향 변환

#### 판다스
Pandas는 파이썬에서 데이터 분석 및 조작을 위한 강력하고 유연한 오픈 소스 라이브러리. Series와 DataFrame 같은 고수준의 데이터 구조를 제공하여, 복잡한 데이터 조작을 직관적이고 효율적으로 수행할 수 있게 한다.

[Pandas의 주요 역할과 기능]

* DataFrame과 Series: 2차원 테이블과 1차원 배열 형태의 데이터 구조를 제공
* 데이터 처리: 결측값 처리, 데이터 정제, 필터링, 병합, 연결 및 변환 등을 위한 다양한 기능을 제공
* 데이터 분석: 기술통계, 그룹화, 시계열 분석 등 복잡한 분석 작업을 제공
* 입출력 기능: CSV, Excel, SQL, JSON 등 다양한 파일 형식의 데이터를 읽고 쓸 수 있는 기능을 제공
* 시각화 지원: 매트플롯립과 연동하여 데이터 시각화가 가능하도록 제공
* 라이브러리는 여러 종류의 class와 다양한 내장 함수로 구성. 시리즈와 데이터프레임은 대표적인 클래스 객체임
* 시리즈 인덱스는 데이터 값과 일대일 대응. 파이썬 딕셔너리와 비슷한 구조. pandas.Series(딕셔너리)

In [ ]:
# 시리즈 클래스 만들기
# pandas 불러오기
import pandas as pd

#k:v 구조를 갖는 딕셔너리를 만들고 변수 dict_data에 저장
dict_data = {'a':1, 'b':2, 'c':3}

sr = pd.Series(dict_data)
print(sr)
type(sr)

a    1
b    2
c    3
dtype: int64


pandas.core.series.Series

In [ ]:
#리스트를 시리즈로 변환

list_data = ['2019-07-02',3.14, 'ABC', 100, True]
sr = pd.Series(list_data)
print(sr, type(sr))

0    2019-07-02
1          3.14
2           ABC
3           100
4          True
dtype: object <class 'pandas.core.series.Series'>


In [ ]:
#인덱스 및 값
idx = sr.index
val = sr.values
print(idx)
print(val)

RangeIndex(start=0, stop=5, step=1)
['2019-07-02' 3.14 'ABC' 100 True]


In [ ]:
#튜플을 시리즈로 변환
tup_data = ('kevin', '2019-07-02', '남', True)
sr= pd.Series(tup_data)
sr = pd.Series(tup_data, index = ['이름', '생년월일', '성별', '학생여부'])
print(sr)

이름           kevin
생년월일    2019-07-02
성별               남
학생여부          True
dtype: object


In [ ]:
# 인덱싱
import warnings
warnings.filterwarnings('ignore')
print(sr[0])
print(sr['이름'])
print(sr[[1, 2]])

kevin
kevin
생년월일    2019-07-02
성별               남
dtype: object


In [ ]:
#배열
import numpy as np

s1 = np.arange(11, 21, 2)
print(s1, type(s1))
print()
s2 = pd.Series(s1, index=list('abcde'))
print(s2, type(s2))

[11 13 15 17 19] <class 'numpy.ndarray'>

a    11
b    13
c    15
d    17
e    19
dtype: int64 <class 'pandas.core.series.Series'>


Q. 배열을 생성 후 시리즈로 변환하여 아래와 같이 출력하세요:
data = np.arange(1000, 5000, 1000)
state = ['Califonia','Ohio','Oregon','Texas']

In [ ]:
state
Califonia  1000
Ohaio      2000
Oregon     3000
Texas      4000
Name: population, dtype: int32

In [ ]:
import numpy as np
data = np.arange(1000, 5000, 1000)
state = ['Califonia', 'Ohio', 'Orehon', 'Texas']
obj = pd.Series(data,index=state)
obj

Califonia    1000
Ohio         2000
Orehon       3000
Texas        4000
dtype: int64

In [ ]:
print(s2, type(s2))

a    11
b    13
c    15
d    17
e    19
dtype: int64 <class 'pandas.core.series.Series'>


In [ ]:
list_form_series = s2.tolist()
list_form_series

[11, 13, 15, 17, 19]

In [ ]:
df_form_series = s2.to_frame(name='Value')
df_form_series

Value
a     11
b     13
c     15
d     17
e     19

In [ ]:
df_form_series = s2.to_dict()
df_form_series

{'a': 11, 'b': 13, 'c': 15, 'd': 17, 'e': 19}

Q. 아래 시리즈에서 null값을 2개 입력 후 그 값을 0으로 대체 후 null값 여부를 확인한 후 출력하세요.


In [ ]:
import pandas as pd
import numpy as np

# 1. Series 생성
s = pd.Series([5, 15, 25, 35, 45], index=['x', 'y', 'z', 'w', 'v'])

In [ ]:
import pandas as pd
import numpy as np

s = pd.Series([5, 15, 25, 35, 45], index=['x', 'y', 'z', 'w', 'v'])

s['x'] = np.nan
s['z'] = np.nan

s = s.fillna(0)

null_check = s.isnull()

print(s)
print(null_check)

x     0.0
y    15.0
z     0.0
w    35.0
v    45.0
dtype: float64
x    False
y    False
z    False
w    False
v    False
dtype: bool


Q. 주어진 리스트 [1, 2, 3, 4, 5]를 Pandas Series로 변환하고, 각 원소에 10을 더한 Series를 출력하세요.

In [ ]:
import pandas as pd

# 주어진 리스트
data_list = [1, 2, 3, 4, 5]

In [ ]:
import pandas as pd

data_list = [1, 2, 3, 4, 5]
data_series = pd.Series(data_list)

result_series = data_series + 10

print(result_series)

0    11
1    12
2    13
3    14
4    15
dtype: int64


Q. Series [10, 20, 30, 40, 50]를 생성하고 인덱스를 ['a', 'b', 'c', 'd', 'e']로 설정하세요. 인덱스를 기준으로 Series를 정렬한 결과를 출력하세요.

In [ ]:
import pandas as pd

data = [10, 20, 30, 40, 50]
index = ['a', 'b', 'c', 'd', 'e']
series = pd.Series(data, index=index)

sorted_series = series.sort_index()

print(sorted_series)

a    10
b    20
c    30
d    40
e    50
dtype: int64


Q. Series ['a':1, 'b':2, 'c':3, 'd':4, 'e':5]에서 인덱스 'b', 'd'에 해당하는 원소를 선택하여 출력하세요.

In [ ]:
import pandas as pd

# 주어진 데이터와 인덱스
data = [1, 2, 3, 4, 5]
index = ['a', 'b', 'c', 'd', 'e']

In [ ]:
import pandas as pd

data = [1, 2, 3, 4, 5]
index = ['a', 'b', 'c', 'd', 'e']
series = pd.Series(data, index=index)

selected_elements = series[['b', 'd']]

print(selected_elements)

b    2
d    4
dtype: int64


#### 데이터프레임
* 데이터프레임은 2차원 배열. R의 데이터프레임에서 유래.
* 데이터프레임의 열은 각각 시리즈 개체.
* 시리즈를 열벡터라고 하면 데이터프레임은 여러개의 열벡터들이 같은 행 인덱스를
  기준으로 줄지어 결합된 2차원 벡터 또는 행렬.
* 선형대수학에서 열 벡터(m x 1 행렬)는 m 원소들의 단일 열 행렬
* 행 벡터(1 x m 행렬)은 m원소들의 단일 행 행렬.
* 리스트, 딕셔너리, ndarray 등 다양한 데이터로부터 생성
* 반대로 리스트, 딕셔너리, ndarray 등으로 변환될 수 있음

In [ ]:
# 배열을 데이터프레임으로 변환
import numpy as np
import pandas as pd
np.random.seed(0)
data = np.random.randint(100, 120, size=(3,3))
print(data, type(data))

df = pd.DataFrame(data,index=['d1', 'd2', 'd3'],
                  columns = ['pd', 'sales', 'inv'])

df

[[112 115 100]
 [103 103 107]
 [109 119 118]] <class 'numpy.ndarray'>


pd  sales  inv
d1  112    115  100
d2  103    103  107
d3  109    119  118

In [ ]:
print(df.pd, type(df.pd))

d1    112
d2    103
d3    109
Name: pd, dtype: int64 <class 'pandas.core.series.Series'>


In [ ]:
df = pd.DataFrame(data, columns = ['pd', 'sales', 'inv'])
df

pd  sales  inv
0  112    115  100
1  103    103  107
2  109    119  118

#### Pandas의 iloc와 loc 메서드
DataFrame과 Series에서 데이터의 특정 위치나 라벨에 접근하기 위한 중요한 도구이며 두 메서드는 각각 고유한 용도를 가지고 있다.

- iloc (Integer Location)
  - 정수 인덱스 기반으로 데이터에 접근하는 메서드. 즉, DataFrame이나 Series의 특정 위치에 있는 데이터를 선택할 때 사용.
  - 슬라이싱 지원: Python 리스트와 유사하게 슬라이싱을 지원.
  - 끝점 포함하지 않음: 슬라이싱 시 끝점은 포함하지 않는다.
- loc (Label Location)
  - 라벨 인덱스 기반으로 데이터에 접근하는 메서드. 즉, DataFrame이나 Series의 라벨 이름을 사용하여 데이터에 접근.
  - 슬라이싱 지원: 라벨을 사용하여 슬라이싱을 지원.
  - 양 끝점 포함: 슬라이싱 시 끝점을 포함.

In [ ]:
import pandas as pd

# 데이터 프레임 생성
data = {
    'A': [1, 2, 3, 4],
    'B': [5, 6, 7, 8],
    'C': [9, 10, 11, 12]
}
df = pd.DataFrame(data)
print(df,'\n')
# 첫번쨰 행, 두번째 열의 값 선택
print(df.iloc[0, 1])   # 출력: 5
# 첫번째부터 두번째 행, 첫번째부터 두번째 열 선택
print(df.iloc[0:2, 0:2])

   A  B   C
0  1  5   9
1  2  6  10
2  3  7  11
3  4  8  12 

5
   A  B
0  1  5
1  2  6


In [ ]:
#데이터 프레임 생성
data = {
    'A': [1, 2, 3, 4],
    'B': [5, 6, 7, 8],
    'C': [9, 10, 11, 12]
}
df = pd.DataFrame(data, index=['a', 'b', 'c', 'd'])
print(df,'\n')
# 인덱스 'a', 열의 'B'의 값 선택
print(df.loc['a', 'B'])  # 출력 : 5

# 인덱스 'a'부터 'b', 열 'A'부터 'B'
print(df.loc['a':'b', 'A':'B'])

   A  B   C
a  1  5   9
b  2  6  10
c  3  7  11
d  4  8  12 

5
   A  B
a  1  5
b  2  6


In [ ]:
df = pd.DataFrame(data,index=['d1', 'd2', 'd3'],
                  columns = ['pd', 'sales', 'inv'])
print(df.iloc[1],'\n')
print(df.loc['d2'])

pd       NaN
sales    NaN
inv      NaN
Name: d2, dtype: object 

pd       NaN
sales    NaN
inv      NaN
Name: d2, dtype: object


In [ ]:
print(df.iloc[1,:], '\n')
print(df.loc['d2',:])

pd       NaN
sales    NaN
inv      NaN
Name: d2, dtype: object 

pd       NaN
sales    NaN
inv      NaN
Name: d2, dtype: object


In [ ]:
import numpy as np
import pandas as pd
np.random.seed(0)
data = np.random.randint(100, 120, size=(3,3))
print(data, type(data))

df = pd.DataFrame(data,index=['d1', 'd2', 'd3'],
                  columns = ['pd', 'sales', 'inv'])
print(df.iloc[1,2])
print(df.loc['d2', 'inv'])

[[112 115 100]
 [103 103 107]
 [109 119 118]] <class 'numpy.ndarray'>
107
107


In [ ]:
df.loc['d3']= 0
df

pd  sales  inv
d1  112    115  100
d2  103    103  107
d3    0      0    0

In [ ]:
df.loc['d4']= 0
df

pd  sales  inv
d1  112    115  100
d2  103    103  107
d3    0      0    0
d4    0      0    0

In [ ]:
import numpy as np
import pandas as pd
np.random.seed(0)
data = np.random.randint(100, 120, size=(3,3))
print(data, type(data))

df = pd.DataFrame(data,index=['d1', 'd2', 'd3'],
                  columns = ['pd', 'sales', 'inv'])
df.loc[:, 'profit'] = 10
df

[[112 115 100]
 [103 103 107]
 [109 119 118]] <class 'numpy.ndarray'>


pd  sales  inv  profit
d1  112    115  100      10
d2  103    103  107      10
d3  109    119  118      10

[파이썬 random 함수]

In [ ]:
import random
print(random.random(),'\n') # 0.0 <= x < 1.0 사이
print(random.randint(1,10),'\n') # 1에서 10사이의 정수중에서 난수 값 리턴
print(random.uniform(10,20), '\n') # min max 사이 float 리턴
print(random.randrange(10), '\n') # 지정 범위 int 리턴
print(random.choice([1,2,3,4,5]),'\n') # 리스트 내부에 있는 요소를 랜덤하게 선택
li = [1,2,3,4,5]
print(random.sample(li,3),'\n') # 리스트 요소를 중복이 안되게 리턴
random.shuffle(li) # 리스트 요소를 다시 섞어서 리턴
print(li)

0.9688348392951813 

6 

15.834879067419305 

7 

2 

[3, 1, 2] 

[2, 5, 1, 4, 3]


[numpy random 함수]

- np.random.seed : seed를 통한 난수 생성
- np.random.randint : 정수 난수 1개 생성
- np.random.rand : 0부터 1사이의 균일분포에서 난수 매트릭스 배열 생성
- np.random.randn : 가우시안 표준 정규분포에서 난수 매트릭스 배열 생성
- np.random.shuffle : 기존의 데이터의 순서 바꾸기
- np.random.choice : 기존 데이터에서 sampling

In [ ]:
import numpy as np
print(np.random.randint(6), '\n') # 0 ~ 5까지 정수인 난수 1개
print(np.random.randint(1,20),'\n') # 1 ~ 19까지 정수인 난수 1개
print(np.random.randint(10, size=10), '\n') # 0 ~ 9까지 정수인 난수 10개
print(np.random.randint(10,20, size=10),'\n') # 10 ~ 19까지 정수인 난수 10개
print(np.random.randint(10,20, size=(3,5))) # 10 ~ 19까지 정수인 난수로 3행 5열 배열 생성

4 

7 

[8 8 1 6 7 7 8 1 5 9] 

[18 19 14 13 10 13 15 10 12 13] 

[[18 11 13 13 13]
 [17 10 11 19 19]
 [10 14 17 13 12]]


In [ ]:
# id, gender, age, region
import numpy as np
import pandas as pd
id = np.arange(1, 1001)
i1 = pd.Series(id)
gender = np.random.randint(2, size = 1000)
g1 = pd.Series(gender)
age = np.random.randint(1, 101, size = 1000)
a1 = pd.Series(age)
region = np.random.randint(1, 11, size = 1000)
r1 = pd.Series(region)

df = pd.concat([i1, g1, a1, r1], axis=1)
df.rename(columns={0:'id', 1:'gender', 2:'age', 3:'region'}, inplace=True)
df.head()

id  gender  age  region
0   1       0   15       7
1   2       1   26       2
2   3       0   22       5
3   4       1   83       9
4   5       0    5       2

In [ ]:
df.drop([0], axis=0, inplace=True)
df.head()

id  gender  age  region
1   2       0   70       1
2   3       0    2       5
3   4       0   18       9
4   5       1   63       5
5   6       1   48      10

- at은 라벨 기반 인덱싱을 사용.단일 값을 접근할 때 loc접근자 보다 빠르다.
- 여러 값을 동시에 접근하려면 loc 접근자를 사용.

In [ ]:
df.loc[5, 'id']

6

In [ ]:
df.at[5, 'id']

6

In [ ]:
df1 = df.drop(df.at[5,'id'])
df.head(7)

id  gender  age  region
1   2       0   70       1
2   3       0    2       5
3   4       0   18       9
4   5       1   63       5
5   6       1   48      10
6   7       1    9       3
7   8       1   74       3

Task1_0527. 4개의 Series를 결합하여 데이터프레임을 생성하여 출력하세요.
- 출력한 데이터프레임에서 추출하고 싶은 5개의 데이터를 인덱싱하여 출력
- null값을 3개 추가
- null값의 개수를 확인하고 삭제
- 2개의 데이터를 수정
- 1개의 행을 삭제

In [ ]:
df1 = df.copy()
df1.head()

id  gender  age  region
1   2       0   70       1
2   3       0    2       5
3   4       0   18       9
4   5       1   63       5
5   6       1   48      10

In [ ]:
np.random.seed(0)
a =np.random.randint(1,5,size=(10,5))
print(a,type(a))

[[1 4 2 1 4]
 [4 4 4 2 4]
 [2 3 1 4 3]
 [1 1 1 3 2]
 [3 4 4 3 1]
 [2 2 2 2 1]
 [2 1 4 1 4]
 [2 3 4 4 1]
 [3 4 1 2 4]
 [2 4 4 3 4]] <class 'numpy.ndarray'>


In [ ]:
#2차원 리스트를 데이터 프레임으로 변환
list1 = a.tolist()

df1 = pd.DataFrame(list1, columns=['c1', 'c2', 'c3', 'c4', 'c5'])
print(df1.head())

   c1  c2  c3  c4  c5
0   1   4   2   1   4
1   4   4   4   2   4
2   2   3   1   4   3
3   1   1   1   3   2
4   3   4   4   3   1


In [ ]:
#데이터 프레임을 배열, 리스트, 딕셔너리로 변환
ar = df1.values
print(ar,type(ar))
print()
li = ar.tolist()
print(li, type(li))
print()
dict = df1.to_dict('list')
print(dict, type(dict))

[[1 4 2 1 4]
 [4 4 4 2 4]
 [2 3 1 4 3]
 [1 1 1 3 2]
 [3 4 4 3 1]
 [2 2 2 2 1]
 [2 1 4 1 4]
 [2 3 4 4 1]
 [3 4 1 2 4]
 [2 4 4 3 4]] <class 'numpy.ndarray'>

[[1, 4, 2, 1, 4], [4, 4, 4, 2, 4], [2, 3, 1, 4, 3], [1, 1, 1, 3, 2], [3, 4, 4, 3, 1], [2, 2, 2, 2, 1], [2, 1, 4, 1, 4], [2, 3, 4, 4, 1], [3, 4, 1, 2, 4], [2, 4, 4, 3, 4]] <class 'list'>

{'c1': [1, 4, 2, 1, 3, 2, 2, 2, 3, 2], 'c2': [4, 4, 3, 1, 4, 2, 1, 3, 4, 4], 'c3': [2, 4, 1, 1, 4, 2, 4, 4, 1, 4], 'c4': [1, 2, 4, 3, 3, 2, 1, 4, 2, 3], 'c5': [4, 4, 3, 2, 1, 1, 4, 1, 4, 4]} <class 'dict'>


결측치 처리 방법

In [2]:
import pandas as pd
import numpy as np

# 예제 데이터프레임 생성
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [np.nan, 2, 3, np.nan, 5],
    'C': [1, np.nan, np.nan, 4, 5],
    'D': [1, 2, 3, 4, 5]
}

df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

Original DataFrame:
     A    B    C  D
0  1.0  NaN  1.0  1
1  2.0  2.0  NaN  2
2  NaN  3.0  NaN  3
3  4.0  NaN  4.0  4
4  5.0  5.0  5.0  5


In [3]:
# null 값을 0으로 채우기
df_filled_zero = df.fillna(0)
print(df_filled_zero)

     A    B    C  D
0  1.0  0.0  1.0  1
1  2.0  2.0  0.0  2
2  0.0  3.0  0.0  3
3  4.0  0.0  4.0  4
4  5.0  5.0  5.0  5


In [4]:
# null 값을 각 열의 평균값으로 채우기
df_filled_mean = df.apply(lambda x: x.fillna(x.mean()), axis=0)
print(df_filled_mean)

     A         B         C  D
0  1.0  3.333333  1.000000  1
1  2.0  2.000000  3.333333  2
2  3.0  3.000000  3.333333  3
3  4.0  3.333333  4.000000  4
4  5.0  5.000000  5.000000  5


In [5]:
# null 값을 각 열의 중간값으로 채우기
df_filled_median = df.apply(lambda x: x.fillna(x.median()), axis=0)
print(df_filled_median)

     A    B    C  D
0  1.0  3.0  1.0  1
1  2.0  2.0  4.0  2
2  3.0  3.0  4.0  3
3  4.0  3.0  4.0  4
4  5.0  5.0  5.0  5


In [7]:
# null 값이 포함된 행 삭제하기
df_dropped_rows = df.dropna()
print(df_dropped_rows)

     A    B    C  D
4  5.0  5.0  5.0  5


In [8]:
# null 값이 포함된 열 삭제하기
df_droppde_dolumns = df.dropna(axis=1)
print(df_droppde_dolumns)

   D
0  1
1  2
2  3
3  4
4  5


In [9]:
# 앞 또는 뒤의 값으로 채우기
df_ffill = df.fillna(method='ffill')
print(df_ffill, '\n')

df_bfill = df.fillna(method='bfill')
print(df_bfill)

     A    B    C  D
0  1.0  NaN  1.0  1
1  2.0  2.0  1.0  2
2  2.0  3.0  1.0  3
3  4.0  3.0  4.0  4
4  5.0  5.0  5.0  5 

     A    B    C  D
0  1.0  2.0  1.0  1
1  2.0  2.0  4.0  2
2  4.0  3.0  4.0  3
3  4.0  5.0  4.0  4
4  5.0  5.0  5.0  5


In [13]:
#  replace 메서드를 사용하여 null 값을 다른 값으로 대체
import pandas as pd
import numpy as np

# 예제 데이터프레임 생성
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [np.nan, 2, 3, np.nan, 5],
    'C': [1, np.nan, np.nan, 4, 5],
    'D': [1, 2, 3, 4, 5]
}

df= pd.DataFrame(data)
print(df)

     A    B    C  D
0  1.0  NaN  1.0  1
1  2.0  2.0  NaN  2
2  NaN  3.0  NaN  3
3  4.0  NaN  4.0  4
4  5.0  5.0  5.0  5


In [14]:
#  replace 메서드를 사용하여 null 값을 다른 값으로 대체
df_replace_zero = df.replace(np.nan, 0)
print(df_replace_zero, '\n')

# replace를 사용하여 null 값을 특정 값으로 대체
df_replace_valud = df.replace(np.nan, -1)
print(df_replace_valud)

     A    B    C  D
0  1.0  0.0  1.0  1
1  2.0  2.0  0.0  2
2  0.0  3.0  0.0  3
3  4.0  0.0  4.0  4
4  5.0  5.0  5.0  5 

     A    B    C  D
0  1.0 -1.0  1.0  1
1  2.0  2.0 -1.0  2
2 -1.0  3.0 -1.0  3
3  4.0 -1.0  4.0  4
4  5.0  5.0  5.0  5


In [ ]:
import pandas as pd

file_Data = pd.DataFrame({
    'col1': [1, 2, 3, 4, 5, 6],
    'col2': ['A', 'A', 'B', 'B', 'C', 'C']
})

print(file_Data)

   col1 col2
0     1    A
1     2    A
2     3    B
3     4    B
4     5    C
5     6    C


In [ ]:
file_Data.to_csv('file_data.csv', index=None)

In [ ]:
!ls

file_data.csv  sample_data


In [ ]:
file_data=pd.read_csv('file_data.csv')
print(file_data, type(file_data))

   col1 col2
0     1    A
1     2    A
2     3    B
3     4    B
4     5    C
5     6    C <class 'pandas.core.frame.DataFrame'>


In [ ]:
df_1 = pd.DataFrame({
    'col1':np.array([1,2,3]),
    'col2':np.array(['A','B','C'])
})
df_2 = pd.DataFrame({
    'col1':np.array([4,5,6]),
    'col2':np.array(['D','E','F'])
})
print(df_1)
print()
print(df_2)

   col1 col2
0     1    A
1     2    B
2     3    C

   col1 col2
0     4    D
1     5    E
2     6    F


In [ ]:
#Q. df_1과 df_2를 행방향과 열방향으로 병합하여 출력하세요.
df_3=pd.concat([df_1,df_2], axis=1)
df_4=pd.concat([df_1,df_2])
print(df_3)
print()
print(df_4)

   col1 col2  col1 col2
0     1    A     4    D
1     2    B     5    E
2     3    C     6    F

   col1 col2
0     1    A
1     2    B
2     3    C
0     4    D
1     5    E
2     6    F


In [ ]:
df_4.iloc[:,1]

0    A
1    B
2    C
0    D
1    E
2    F
Name: col2, dtype: object

In [ ]:
df_4[['col2']]

col2
0    A
1    B
2    C
0    D
1    E
2    F

In [ ]:
# 데이터프레임 생성(8행 5열)
import numpy as np
import pandas as pd

np.random.seed(3)
data = np.random.randint(50,100,size=(8,5))

df = pd.DataFrame(data, columns=list('abcde'))
df

a   b   c   d   e
0  92  74  53  58  50
1  71  69  60  93  91
2  60  71  88  82  70
3  94  79  89  64  76
4  67  76  72  52  52
5  51  76  55  90  96
6  83  79  92  74  57
7  93  83  65  98  87

In [ ]:
# 열 이름과 행 이름 변경
columns={'a':'국어','b':'영어','c':'수학','d':'과학','e':'음악'}
index={0:'a',1:'b',2:'c',3:'d',4:'e',5:'f',6:'g',7:'h'}
df.rename(columns=columns, index=index, inplace=True)
df

국어  영어  수학  과학  음악
a  92  74  53  58  50
b  71  69  60  93  91
c  60  71  88  82  70
d  94  79  89  64  76
e  67  76  72  52  52
f  51  76  55  90  96
g  83  79  92  74  57
h  93  83  65  98  87

In [ ]:
# 데이터프레임 생성
import numpy as np
import pandas as pd
np.random.seed(0)

data = np.random.randint(80,100,size=(5,5))
df = pd.DataFrame(data, columns=list('abcde'))
df

a   b   c   d   e
0  92  95  80  83  83
1  87  89  99  98  84
2  86  92  81  86  87
3  94  97  85  93  88
4  89  99  96  99  85

In [ ]:
df1=df.copy()
df1

a   b   c   d   e
0  92  95  80  83  83
1  87  89  99  98  84
2  86  92  81  86  87
3  94  97  85  93  88
4  89  99  96  99  85

In [ ]:
df1['index'] = list('가나다라마')
df1

a   b   c   d   e index
0  92  95  80  83  83     가
1  87  89  99  98  84     나
2  86  92  81  86  87     다
3  94  97  85  93  88     라
4  89  99  96  99  85     마

In [ ]:
df2 = df1.set_index('index')
df2

a   b   c   d   e
index                    
가      92  95  80  83  83
나      87  89  99  98  84
다      86  92  81  86  87
라      94  97  85  93  88
마      89  99  96  99  85

In [ ]:
df21 = df2.drop('e', axis=1)
df21

a   b   c   d
index                
가      92  95  80  83
나      87  89  99  98
다      86  92  81  86
라      94  97  85  93
마      89  99  96  99

In [ ]:
df3 = df2.reset_index()
df3

index   a   b   c   d   e
0     가  92  95  80  83  83
1     나  87  89  99  98  84
2     다  86  92  81  86  87
3     라  94  97  85  93  88
4     마  89  99  96  99  85

In [ ]:
new_index = ['r0', 'r1', 'r2', 'r3', 'r4', 'r5', 'r6', 'r7', 'r8']
df5 = df.reindex(new_index,fill_value=0)
df5

a  b  c  d  e
r0  0  0  0  0  0
r1  0  0  0  0  0
r2  0  0  0  0  0
r3  0  0  0  0  0
r4  0  0  0  0  0
r5  0  0  0  0  0
r6  0  0  0  0  0
r7  0  0  0  0  0
r8  0  0  0  0  0

In [ ]:
new_index = ['r0', 'r1', 'r2', 'r3', 'r4']
df1 = df5.reindex(new_index)
df1

a  b  c  d  e
r0  0  0  0  0  0
r1  0  0  0  0  0
r2  0  0  0  0  0
r3  0  0  0  0  0
r4  0  0  0  0  0

In [ ]:
df1 = df5.drop(df5.index[5:9])
df1

a  b  c  d  e
r0  0  0  0  0  0
r1  0  0  0  0  0
r2  0  0  0  0  0
r3  0  0  0  0  0
r4  0  0  0  0  0

In [ ]:
# Q. df5에서 r5~r8까지 삭제 후 df1으로 출력하세요.
df1 = df5.drop(['r5', 'r6', 'r7', 'r8'], axis=0)
df1

a  b  c  d  e
r0  0  0  0  0  0
r1  0  0  0  0  0
r2  0  0  0  0  0
r3  0  0  0  0  0
r4  0  0  0  0  0

In [ ]:
df1_s =df1.sort_index(ascending=False)
df1_s

a  b  c  d  e
r4  0  0  0  0  0
r3  0  0  0  0  0
r2  0  0  0  0  0
r1  0  0  0  0  0
r0  0  0  0  0  0

In [ ]:
df1_c = df1.sort_values(by='c', ascending=False)
df1_c

a  b  c  d  e
r0  0  0  0  0  0
r1  0  0  0  0  0
r2  0  0  0  0  0
r3  0  0  0  0  0
r4  0  0  0  0  0

In [ ]:
# 전치
df1_t = df1.transpose()
df1_t

r0  r1  r2  r3  r4
a   0   0   0   0   0
b   0   0   0   0   0
c   0   0   0   0   0
d   0   0   0   0   0
e   0   0   0   0   0

In [ ]:
# 딕셔서리를 정의
dict_data = {'a':[1,2,3,4,5], 'b':[4,5,6,7,8], 'c':[7,8,9,10,11], 'd':[10,11,12,13,14], 'e':[13,14,15,16,17]}

# 딕셔서리를 데이터프레임으로 변환. 인덱스를 [r0, r1, r2]로 지정
df = pd.DataFrame(dict_data, index=['r0','r1','r2','r3','r4'])
df

a  b   c   d   e
r0  1  4   7  10  13
r1  2  5   8  11  14
r2  3  6   9  12  15
r3  4  7  10  13  16
r4  5  8  11  14  17

In [ ]:
df1 =df1_t.transpose()
df1

a  b  c  d  e
r0  0  0  0  0  0
r1  0  0  0  0  0
r2  0  0  0  0  0
r3  0  0  0  0  0
r4  0  0  0  0  0

In [ ]:
Q. df1으로 데이터프레임을 생성한 후 set_index를 사용하여 ID를 인덱스 설정한 데이터프레임을 출력하세요.

df1 = pd.DataFrame({
    'ID': [101, 102, 103, 104],
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [24, 27, 22, 32]
})

In [ ]:
import pandas as pd

df1 = pd.DataFrame({
    'ID': [101, 102, 103, 104],
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [24, 27, 22, 32]
})

df1.set_index('ID', inplace=True)
df1.head(2)

Name  Age
ID             
101  Alice   24
102    Bob   27

In [ ]:
Q. df2에 대해서 다음을 수행하세요.
- set_index를 사용하여 인덱스를 설정.
- reset_index를 사용하여 인덱스를 리셋.

df2 = pd.DataFrame({
    'ID': [101, 102, 103, 104],
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [24, 27, 22, 32]
})

In [ ]:
import pandas as pd

df2 = pd.DataFrame({
    'ID': [101, 102, 103, 104],
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [24, 27, 22, 32]
})


df2_set_index = df2.set_index('ID')
print("Set Index:\n", df2_set_index)

df2_reset_index = df2_set_index.reset_index()
print("\nReset Index:\n", df2_reset_index)

Set Index:
         Name  Age
ID               
101    Alice   24
102      Bob   27
103  Charlie   22
104    David   32

Reset Index:
     ID     Name  Age
0  101    Alice   24
1  102      Bob   27
2  103  Charlie   22
3  104    David   32


In [ ]:
Q. df3에 대해서 reindex를 사용하여 인덱스를 변경하여 출력하세요.

df3 = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [24, 27, 22, 32]
}, index=[101, 102, 103, 104])

In [ ]:
import pandas as pd

df3 = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [24, 27, 22, 32]
}, index=[101, 102, 103, 104])

new_index = [201, 202, 203, 204]
df3_reindexed = df3.reindex(new_index)

print(df3_reindexed)

    Name  Age
201  NaN  NaN
202  NaN  NaN
203  NaN  NaN
204  NaN  NaN


In [ ]:
Q. df4에 대해서 reindex를 사용하여 인덱스를 변경하고 결측치를 0으로 채운 데이터프레임을 출력하세요.

df4 = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [24, 27, 22]
}, index=[0, 1, 2])

print("기존 인덱스:\n", df4)

In [ ]:
import pandas as pd

df4 = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [24, 27, 22]
}, index=[0, 1, 2])

print("기존 인덱스:\n", df4)

new_index = [0, 1, 2, 3, 4]

df4_reindexed = df4.reindex(new_index).fillna(0)

print("변경된 인덱스와 결측치가 0으로 채워진 데이터프레임:\n", df4_reindexed)

기존 인덱스:
       Name  Age
0    Alice   24
1      Bob   27
2  Charlie   22
변경된 인덱스와 결측치가 0으로 채워진 데이터프레임:
       Name   Age
0    Alice  24.0
1      Bob  27.0
2  Charlie  22.0
3        0   0.0
4        0   0.0


In [ ]:
Q. df5에서 reindex를 사용하여 특정 날짜 범위로 인덱스를 재설정하여 출력하세요.

dates = pd.date_range('2024-01-01', periods=4, freq='D')
df5 = pd.DataFrame({
    'Value': [10, 20, 30, 40]
}, index=dates)

In [ ]:
import pandas as pd

dates = pd.date_range('2024-01-01', periods=4, freq='D')
df5 = pd.DataFrame({
    'Value': [10, 20, 30, 40]
}, index=dates)

new_dates = pd.date_range('2024-01-01', '2024-01-05')

df5_reindexed = df5.reindex(new_dates)

print(df5_reindexed)

            Value
2024-01-01   10.0
2024-01-02   20.0
2024-01-03   30.0
2024-01-04   40.0
2024-01-05    NaN


In [18]:
#Q. 데이터프레임 df6를 전치하고, 전치된 데이터프레임을 정리하여 연도별 판매량 데이터를 제품별로 나열하여 출력하세요.

data = {
    'Year': ['2020', '2021', '2022'],
    'Product_A': [500, 600, 700],
    'Product_B': [400, 500, 600],
    'Product_C': [300, 400, 500]
}
df6 = pd.DataFrame(data)
df6

Year  Product_A  Product_B  Product_C
0  2020        500        400        300
1  2021        600        500        400
2  2022        700        600        500

In [19]:
import pandas as pd

data = {
    'Year': ['2020', '2021', '2022'],
    'Product_A': [500, 600, 700],
    'Product_B': [400, 500, 600],
    'Product_C': [300, 400, 500]
}
df6 = pd.DataFrame(data)

df_transposed = df6.transpose()

new_header = df_transposed.iloc[0]
df_transposed = df_transposed[1:]
df_transposed.columns = new_header

df_transposed.reset_index(inplace=True)
df_transposed.rename(columns={'index': 'Product'}, inplace=True)

print(df_transposed)

Year    Product 2020 2021 2022
0     Product_A  500  600  700
1     Product_B  400  500  600
2     Product_C  300  400  500


In [20]:
df6.set_index('Year', inplace=True)

In [21]:
df6

Product_A  Product_B  Product_C
Year                                 
2020        500        400        300
2021        600        500        400
2022        700        600        500

In [23]:
df6.index.name = None
df6

Product_A  Product_B  Product_C
2020        500        400        300
2021        600        500        400
2022        700        600        500

In [22]:
df_transposed =df6.T
print(df_transposed)

Year       2020  2021  2022
Product_A   500   600   700
Product_B   400   500   600
Product_C   300   400   500


In [24]:
df_transposed.reset_index(inplace=True)
df_transposed

index  2020  2021  2022
0  Product_A   500   600   700
1  Product_B   400   500   600
2  Product_C   300   400   500

In [25]:
df_transposed.rename(columns={'index':'Preoduct'}, inplace=True)
df_transposed

Preoduct  2020  2021  2022
0  Product_A   500   600   700
1  Product_B   400   500   600
2  Product_C   300   400   500