<a href="https://colab.research.google.com/github/windyday0622/windyday/blob/main/m3_%EB%B6%84%EC%84%9D%20%EB%9D%BC%EC%9D%B4%EB%B8%8C%EB%9F%AC%EB%A6%AC/%20%EA%B3%BC%EC%A0%9C_240611.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Task1_0611. 주어진 대각 행렬의 역행렬을 구하고, 역행렬이 맞는지 확인하세요.

D = np.diag([1, 2, 3])

In [2]:
import numpy as np

D = np.diag([1, 2, 3])

D_inv = np.linalg.inv(D)

identity_check = np.dot(D, D_inv)

print("D:")
print(D)
print("\nD의 역행렬 D_inv:")
print(D_inv)
print("\nD와 D_inv의 곱:")
print(identity_check)

D:
[[1 0 0]
 [0 2 0]
 [0 0 3]]

D의 역행렬 D_inv:
[[1.         0.         0.        ]
 [0.         0.5        0.        ]
 [0.         0.         0.33333333]]

D와 D_inv의 곱:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Task2_0611. 임의의 상삼각 행렬을 생성하고, 그 행렬로 부터 하삼각 행렬을 구하여 출력하세요.

In [9]:
import numpy as np

# 임의의 자연수를 사용하여 상삼각 행렬 생성
def generate_upper_triangular_matrix(n):
    # 1부터 100까지의 자연수로 n x n 행렬 생성
    matrix = np.random.randint(1, 101, size=(n, n))
    # 상삼각 행렬로 변환
    upper_triangular_matrix = np.triu(matrix)
    return upper_triangular_matrix

# 상삼각 행렬로부터 하삼각 행렬 추출
def extract_lower_triangular_matrix(matrix):
    lower_triangular_matrix = np.tril(matrix)
    return lower_triangular_matrix

# 행렬 크기 지정
n = 4

# 상삼각 행렬 생성
upper_triangular_matrix = generate_upper_triangular_matrix(n)
print("상삼각 행렬:")
print(upper_triangular_matrix)

# 하삼각 행렬 추출
lower_triangular_matrix = extract_lower_triangular_matrix(upper_triangular_matrix)
print("\n하삼각 행렬:")
print(lower_triangular_matrix)

상삼각 행렬:
[[ 63 100  52  87]
 [  0  69  23  37]
 [  0   0  62  27]
 [  0   0   0  64]]

하삼각 행렬:
[[63  0  0  0]
 [ 0 69  0  0]
 [ 0  0 62  0]
 [ 0  0  0 64]]


Task3_0611. 주어진 행렬의 역행렬을 구하고, 역행렬이 맞는지 확인하세요.

A = np.array([[4, 7], [2, 6]])

In [6]:
import numpy as np

# 행렬 A 정의
A = np.array([[4, 7], [2, 6]])

# A의 역행렬 계산
A_inv = np.linalg.inv(A)

# A_inv가 A의 역행렬인지 확인 (A @ A_inv가 단위 행렬인지 확인)
identity_check = np.allclose(np.dot(A, A_inv), np.eye(A.shape[0]))

print("A의 역행렬:")
print(A_inv)
print("역행렬 확인 결과:", identity_check)

A의 역행렬:
[[ 0.6 -0.7]
 [-0.2  0.4]]
역행렬 확인 결과: True


Task4_0611. 주어진 데이터 포인트와 모델 파라미터를 사용하여 선형 회귀 모델의 예측값을 계산하세요.

X = np.array([1, 2, 3])

- 1단계 : 주어진 입력 데이터 포인트 X와 모델 파라미터 θ를 정의.
- 2단계 : 행렬 곱을 사용하여 예측값 y를 계산.

In [5]:
import numpy as np

# 1단계: 주어진 입력 데이터 포인트 X와 모델 파라미터 θ를 정의
X = np.array([1, 2, 3])
theta = np.array([0.5, 1.5, 2.5])

# 2단계: 행렬 곱을 사용하여 예측값 y를 계산
y = np.dot(X, theta)

print("입력 데이터 X:", X)
print("모델 파라미터 θ:", theta)
print("예측값 y:", y)

입력 데이터 X: [1 2 3]
모델 파라미터 θ: [0.5 1.5 2.5]
예측값 y: 11.0


Task5_0611. 주어진 입력 벡터와 가중치 행렬을 사용하여 신경망의 단일 계층 출력을 계산하세요.
X = np.array([0.5, 1.0, -1.5])
- 1단계: 입력 벡터 X와 가중치 행렬 W를 정의.
- 2단계: 행렬 곱을 사용하여 계층의 출력을 계산.

In [4]:
import numpy as np

# 입력 벡터 X
X = np.array([0.5, 1.0, -1.5])

# 가중치 행렬 W (예시로 3x2 행렬을 사용)
W = np.array([
    [0.2, -0.3],
    [0.4, 0.1],
    [-0.5, 0.2]
])

# 계층의 출력 계산
output = np.dot(X, W)

print(output)

[ 1.25 -0.35]


Task6_0611. 주어진 입력 벡터에 대해 신경망의 활성화 함수(ReLU, 시그모이드)를 적용하여 출력을 계산하세요.

X = np.array([1, -2, 3])

- 1단계: 입력 벡터 X를 정의.
- 2단계: 가중치 행렬 W와 편향 벡터 b를 정의.
- 3단계: 활성화 함수(ReLU, 시그모이드)를 적용하여 출력을 계산
활성화 함수 적용<br>
output_relu = relu(Z)<br>
output_sigmoid = sigmoid(Z)

In [3]:
import numpy as np

# 입력 벡터 X를 정의
X = np.array([1, -2, 3])

# 가중치 행렬 W와 편향 벡터 b를 정의
W = np.array([[0.2, -0.5, 1.0],
              [1.5, -1.0, 0.5],
              [-0.3, 0.8, -1.2]])

b = np.array([0.5, -0.5, 0.0])

# 활성화 함수(ReLU, 시그모이드)를 정의
def relu(z):
    return np.maximum(0, z)

def sigmoid(z):
    return 1 / (1 + np.exp(-z))

# 선형 변환 Z 계산
Z = np.dot(W, X) + b

# 활성화 함수 적용
output_relu = relu(Z)
output_sigmoid = sigmoid(Z)

print("Output with ReLU:", output_relu)
print("Output with Sigmoid:", output_sigmoid)

Output with ReLU: [4.7 4.5 0. ]
Output with Sigmoid: [0.9909867  0.98901306 0.00407014]


Task7_0611. 주어진 선형 방정식을 행렬 형태로 나타내고, 역행렬을 사용하여
x와 y를 구하세요.

$\begin{cases}
3x + 4y = 10 \\
2x + y = 5
\end{cases}$

단계:
1. 계수 행렬 A와 결과 벡터 b를 정의.
2. 행렬 A의 역행렬을 구한다.
3. 역행렬을 사용하여 변수 x를 구한다.

In [10]:
import numpy as np

A = np.array([[3, 4], [2, 1]])

B = np.array([[10], [5]])

A_inv = np.linalg.inv(A)

X = np.dot(A_inv, B)

print("x =", X[0][0])
print("y =", X[1][0])

x = 2.0
y = 0.9999999999999998


Task8_0611. 주어진 2D 평면의 점을 특정 변환 행렬을 사용하여 변환한 후, 변환된 좌표를 원래 좌표로 되돌리세요.

원래 점의 좌표 p와 변환 행렬 T 정의<br>
p = np.array([1, 2])<br>
T = np.array([[2, 0], [0, 3]])

단계
1. 원래 점의 좌표 p와 변환 행렬 T를 정의.
2. 변환 행렬 T를 사용하여 새로운 좌표 p를 계산.
3. 변환 행렬 T의 역행렬을 사용하여 새로운 좌표 p에서 원래 좌표 p를 복원.

In [11]:
import numpy as np

p = np.array([1, 2])
T = np.array([[2, 0], [0, 3]])

transformed_p = np.dot(T, p)

print("변환된 좌표:", transformed_p)

inverse_T = np.linalg.inv(T)
restored_p = np.dot(inverse_T, transformed_p)

print("복원된 좌표:", restored_p)

변환된 좌표: [2 6]
복원된 좌표: [1. 2.]
