<a href="https://colab.research.google.com/github/windyday0622/windyday/blob/main/m3_%EB%B6%84%EC%84%9D%20%EB%9D%BC%EC%9D%B4%EB%B8%8C%EB%9F%AC%EB%A6%AC/%20%EA%B3%BC%EC%A0%9C_240610.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Task1_0610. 주어진 두 배열 arr1과 arr2에서, arr2의 요소가 10보다 큰 위치의 arr1 요소들을 선택하세요.

arr1 = np.array([10, 20, 30, 40, 50])<br>
arr2 = np.array([5, 15, 25, 10, 35])

In [ ]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([5, 15, 25, 10, 35])

condition = arr2 > 10

result = arr1[condition]

print(result)

[20 30 50]


Task2_0610. 주어진 배열에서 짝수 인덱스에 있는 요소들을 선택하세요.

arr = np.array([5, 10, 15, 20, 25, 30, 35, 40])

In [ ]:
import numpy as np

arr = np.array([5, 10, 15, 20, 25, 30, 35, 40])

result = arr[::2]

print(result)

[ 5 15 25 35]


Task3_0610. 주어진 배열에서 20보다 작은 요소들의 값을 0으로 변경하세요.

arr = np.array([10, 25, 30, 15, 40, 5])

In [ ]:
import numpy as np

arr = np.array([10, 25, 30, 15, 40, 5])
arr[arr < 20] = 0

print(arr)

[ 0 25 30  0 40  0]
