<a href="https://colab.research.google.com/github/windyday0622/windyday/blob/main/m3_%EB%B6%84%EC%84%9D%20%EB%9D%BC%EC%9D%B4%EB%B8%8C%EB%9F%AC%EB%A6%AC/%20%EC%84%A0%ED%98%95%EB%8C%80%EC%88%98.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 선형대수
- 데이터 분석 및 머신 러닝에서 매우 중요한 역할을 한다. 데이터를 벡터와 행렬로 표현하고, 이를 기반으로 다양한 알고리즘을 구현하며, 효율적인 계산을 수행하는 데 필수적.
- 선형대수의 기본 개념을 이해하면 데이터 분석과 머신 러닝의 많은 기법을 더 깊이 이해하고 활용할 수 있다.

#### 벡터 (Vector)

- **정의**: 크기와 방향을 가지는 물리량. 보통 1차원 배열로 표현.
- **용도**: 데이터 포인트를 표현하거나, 특성 벡터(feature vector)로 사용.
- **예시**: $[x_1, x_2, \ldots, x_n]은 n 차원의 벡터.$

#### 행렬 (Matrix)

- **정의**: 행과 열로 구성된 2차원 배열.
- **용도**: 데이터 셋, 변환 행렬, 가중치 행렬 등으로 사용.
- **예시**: $\begin{bmatrix} a & b \\ c & d \end{bmatrix}$ 은 2x2 행렬입니다.

#### 스칼라 (Scalar)

- **정의**: 하나의 수치.
- **용도**: 벡터나 행렬의 요소로 사용.
- **예시**: 5, -3.2 등.

In [3]:
import numpy as np

vector = np.array([1,2,3])
print("Vectoer:", vector)

Vectoer: [1 2 3]


In [5]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Matrix:\n", matrix)

Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
scalar=5
print("scalar:",scalar)

scalar: 5


#### 벡터
일반적으로 데이터를 배열한 형태를 의미하며, 행벡터(row vector)와 열벡터(column vector) 모두를 포함할 수 있습니다. 특정 문맥에 따라 두 가지 형태 중 하나가 선호될 수 있습니다.
- 행벡터 (Row Vector): 행벡터는 하나의 행으로 구성된 벡터.
- 열벡터 (Column Vector): 열벡터는 하나의 열로 구성된 벡터.

벡터의 사용 유형
- 수학적 표기: 수학적 연산이나 이론적 배경에서 행벡터와 열벡터 중 하나를 선택. 예를 들어, 벡터 간의 내적(dot product)은 보통 행벡터와 열벡터의 곱으로 표현.
- 프로그래밍 관습: 프로그래밍 언어나 라이브러리에 따라 벡터를 행벡터나 열벡터로 다루는 방식이 다를 수 있다. 예를 들어, Python의 NumPy에서는 1차원 배열을 벡터로 사용하며, 이를 행벡터나 열벡터로 해석할 수 있다.
- 데이터 형태: 데이터가 테이블 형태로 주어졌을 때, 행(row)이나 열(column)을 벡터로 선택할 수 있다. 일반적으로 데이터베이스나 CSV 파일에서 행이 개별 샘플을 나타내는 경우가 많다.

데이터 분석이나 기계 학습에서는 데이터의 형식과 분석의 편의성에 따라 행벡터나 열벡터를 선택.

In [8]:
# 넘파이를 사용한 벡터 표현 : 벡터를 열 개수가 하나인 2차원 배열 객체로 표현. 배열의 차원(2)은 벡터의 차원(4)과 다른 의미임
# 벡터의 차원은 벡터가 포함하는 요소의 개수를 의미하며, 배열의 차원은 배열이 가지는 축의 수 (행과열)을 의미
import numpy as np
x1 = np.array([[5,1],[3,5],[1,4],[0,2]])
print(x1,x1.shape)

[[5 1]
 [3 5]
 [1 4]
 [0 2]] (4, 2)


벡터는 데이터 분석과 수학, 물리학 등 다양한 분야에서 중요한 역할

- 벡터의 정의
  - 수학적 정의: 크기와 방향을 가진 양입니다. 벡터는 일반적으로 화살표로 표현되며, 시작점에서 끝점까지의 방향과 거리로 정의
  - 좌표로의 표현: 벡터는 종종 숫자의 배열 또는 목록으로 표현. 예를 들어, 2차원 벡터 [x, y]는 x축과 y축에 대한 구성 요소를 갖는다.
  - 크기와 방향: 벡터의 크기는 벡터의 길이 혹은 노름(norm)을 의미하고, 방향은 벡터가 가리키는 방향을 의미.
- 벡터의 연산
  - 덧셈과 뺄셈: 같은 크기의 두 벡터는 각 요소별로 더하거나 뺄 수 있다.
  - 스칼라 곱셈: 벡터는 스칼라(단순 숫자 값)와 곱할 수 있으며, 이는 벡터의 길이를 스칼라만큼 늘리거나 줄인다.
  - 내적(Dot Product): 두 벡터의 각 요소의 곱을 모두 더하는 연산으로, 두 벡터 간의 관계를 측정하는 데 사용.
- 벡터의 응용
  - 물리학: 속도, 가속도, 힘 등은 벡터로 표현.
  - 컴퓨터 그래픽스: 이미지나 애니메이션에서 객체의 위치, 이동, 회전을 표현하는 데 벡터가 사용.
  - 데이터 분석 및 기계 학습: 특징 벡터(feature vector)는 데이터 포인트의 속성을 나타내며, 여러 알고리즘에서 중요한 역할을 한다.


- 벡터의 실용적 예: 데이터 분석에서의 특징 벡터
  - 데이터 포인트의 표현: 예를 들어, 사람에 대한 데이터가 있다고 가정하면 나이, 키, 몸무게 등의 특성을 가진다면, 이를 [나이, 키, 몸무게]와 같은 벡터로 표현할 수 있다. data_point = np.array([나이, 키, 몸무게])
  - 기계 학습 모델의 입력: 이러한 벡터는 기계 학습 모델의 입력으로 사용될 수 있다. 예를 들어, 의료 데이터를 기반으로 질병을 예측하는 모델에서 각 환자의 데이터 포인트는 하나의 벡터로 표현될 수 있다.
- 배치 데이터용 행렬
  - 여러 데이터 포인트를 처리할 때 각 행은 데이터 포인트를 나타내고 각 열은 기능을 나타내는 행렬이 사용된다.
  - batch_data = np.array([[feature1_data1, feature2_data1, feature3_data1],[feature1_data2, feature2_data2, feature3_data2],...])

In [9]:
# 사람의 나이, 키, 몸무게를 백터로 표현
import numpy as np

person = np.array([30, 175, 70])

another_person = np.array([25, 160, 55])

difference = person - another_person
print(difference)

[ 5 15 15]


In [11]:
# Q. 두 행벡터를 정의하고 두 벡터의 합을 구하세요.
def problem1():
    row_vector1 = np.array([1, 2, 3])
    row_vector2 = np.array([4, 5, 6])

    sum_vector = row_vector1 + row_vector2
    print(f"첫 번째 행벡터: {row_vector1}")
    print(f"두 번째 행벡터: {row_vector2}")
    print(f"벡터의 합: {sum_vector}")
problem1()

첫 번째 행벡터: [1 2 3]
두 번째 행벡터: [4 5 6]
벡터의 합: [5 7 9]


In [13]:
import numpy as np

def scalar_multplication_example():
    row_vector = np.array([1, 2, 3])
    column_vector = np.array([[4], [5], [6]])
    scalar = 3

    scaled_row_vector + scalar * row_vector
    scaled_column_vector + scalar * column_vector

    print(f"원래 행벡터: {row_vector}")
    print(f"스칼라 곱셈 후 행벡터: {scaled_row_vector}")
    print("\n")
    print(f"원래 열벡터: {column_vector}")
    print(f"스칼라 곱셈 후 열벡터: \n{scaled_column_vector}")

특징 벡터의 정의 및 용도
- 정의:
  - 특징 벡터는 여러 개의 특성(feature)들로 구성된 벡터.
  - 이 벡터의 각 요소는 데이터의 특정 속성을 나타낸다.
- 용도:
  - 특징 벡터는 머신 러닝 모델의 입력으로 사용.
  - 데이터를 수치적으로 표현하여 모델이 이해할 수 있도록 한다.
  - 다양한 특성을 결합하여 데이터 포인트를 다차원 공간의 한 점으로 표현.

In [15]:
# 특징 벡터 : 데이터 벡터가 예측 문제에서 입력 데이터로 사용되면 특징 벡터라고 함
from sklearn.datasets import load_iris
iris = load_iris()

x1 = iris.data[0, :]
x1

array([5.1, 3.5, 1.4, 0.2])

In [16]:
import pandas as pd
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [17]:
df.iloc[0].values

array([5.1, 3.5, 1.4, 0.2])

In [18]:
ar = df.iloc[[0],:].values
print(ar,ar.shape,type(ar))

[[5.1 3.5 1.4 0.2]] (1, 4) <class 'numpy.ndarray'>


#### 행렬과 벡터
선형대수학에서 매우 중요한 개념으로, 서로 밀접한 관계를 가지고 있으며 그 관계를 이해하기 위한 핵심 개념을 알아야 한다:

벡터의 정의:
- 벡터는 크기와 방향을 가진 수학적 객체. 보통 1차원 배열로 표현.
- 벡터는 n차원 공간에서의 한 점으로 생각할 수 있으며, 좌표로 나타낼 수 있다.
- 예를 들어, 3차원 벡터 $v=[v1,v2,v3]$는 3차원 공간에서의 한 점을 나타낸다.

행렬의 정의:
- 행렬은 수나 변수를 직사각형 배열로 배치한 것입니다. 보통 2차원 배열로 표현.
- 행렬은 m개의 행과 n개의 열로 구성된 $m×n$ 배열이다.

벡터와 행렬의 관계:

- 벡터는 행렬의 특수한 경우로 간주될 수 있다. n차원 벡터는 $1×n$ 행렬(행벡터) 또는 $n×1$ 행렬(열벡터)로 표현할 수 있다.
- 행렬은 여러 벡터를 하나의 구조로 결합한 것이다.
- 예를 들어, 행렬의 각 행이나 열을 벡터로 볼 수 있다. $m×n$ 행렬에서 각 행은 n차원 행벡터이고, 각 열은 m차원 열벡터이다.

행렬과 벡터의 연산:
- 행렬-벡터 곱: 행렬A와 벡터v의 곱은 또 다른 벡터를 생성합니다.  - 예를 들어, A가 m×n 행렬이고 v가 n차원(nx1) 열벡터일 때, Av는 m차원(mx1) 열벡터가 된다.
- 벡터의 내적: 두 벡터 u와 v의 내적은 행벡터 u와 열벡터 v의 곱으로 계산할 수 있고 그 결과는 스칼라 값.

행렬의 역할:
- 벡터에 행렬을 곱하면, 선형 변환을 하여 해당 벡터가 변환된 새로운 벡터를 얻을 수 있다. 예를 들어, 회전 행렬은 벡터를 회전시키는 역할을 한다.
- 데이터셋을 처리할 때, 행렬을 사용하여 여러 데이터 포인트(벡터)를 동시에 변환하거나 조작할 수 있다.
- 신경망에서 각 층은 기본적으로 선형 변환(가중치 행렬)과 비선형 활성화 함수의 조합으로 구성. 선형 변환을 통해 입력 데이터를 다음 계층으로 전달하고, 비선형 활성화 함수를 통해 모델의 표현력을 높인다.

In [19]:
import numpy as np
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

v = np.array([
    [1],
    [0],
    [-1]
])
result = np.dot(A,v)

print(result)

[[-2]
 [-2]]


## 행렬의 종류

- 단위행렬(항등행렬)은 행렬 곱셈 연산에 항등원으로 작용하는 행렬로서 대각선 요소는 모두 1이고, 나머지 요소는 모두 0인 정사각 행렬
- 대각행렬은 주대각선 원소를 제외한 모든 원소들이 0인 정방행렬
- 영행렬은 모든 원소가 0인 행렬로 곱셈 연산에서 영원으로 작용하는 행렬
- 전치행렬은 주대각선 원소를 기준으로 행과 열을 바꿔주는 행렬
- 대칭행렬은 주대각선을 기준으로 대칭을 이루는 행렬로서 전치 행렬이 자기 자신과 같은 행렬
- 정방행렬은 행과 열의 수가 같은 행렬
- 대각합은 정사각 행렬의 대각선 요소의 합
- 역행렬은 원래 행렬 A와 곱할 때 단위 행렬이 되는 행렬
- 삼각행렬은 주대각선 위 또는 아래의 모든 요소가 0인 특별한 종류의 정방행렬
- 상삼각행렬은 대각선 아래 모든 요소가 0인 행렬
- 하삼각행렬은 대각선 위 모든 요소가 0인 행렬

In [26]:
# 항등행렬 : 단위 행렬 또는 항등 행렬은 주대각선의 원소가 모두 1이며 나머지 원소는 모두 0인 정방행렬
um = np.identity(3)

In [32]:
# Q. 단위 행렬을 정의하고, 임의의 행렬과 곱한 후 출력하세요.
def problem1():
    I = np.eye(3)
    print(I,'\n')
    A = np.array([[1,2,3],[4,5,6],[7,8,9]])
    result = np.dot(I,A)

In [33]:
import numpy as np
I = np.eye(3)

print(I,'\n')
print(np.linalg.inv(I),'\n')

print(np.allclose(I, np.linalg.inv(I)))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

True


In [34]:
# 대각행렬: 주대각선 원소들을 제외한 원소들이 모두 0인 정방행렬
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [35]:
# 1부터 5까지의 숫자를 대각선에 갖는 대각행렬을 만드세요

a = np.diag([1, 2, 3, 4, 5])
print(a)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [36]:
# 2부터 10까지의 짝수를 대각선에 갖는 대각행렬을 만드세요

a = np.diag([2, 4, 6, 8, 10])
print(a)

[[ 2  0  0  0  0]
 [ 0  4  0  0  0]
 [ 0  0  6  0  0]
 [ 0  0  0  8  0]
 [ 0  0  0  0 10]]


In [37]:
# Q. 대각행렬을 정의하고, 임의의 벡터와 곱한 후 출력하세요.
import numpy as np

# 대각행렬 정의
diagonal_elements = [1, 2, 3, 4]
diagonal_matrix = np.diag(diagonal_elements)

# 임의의 벡터 정의
vector = np.array([1, 0, -1, 2])

# 대각행렬과 벡터의 곱
result = np.dot(diagonal_matrix, vector)

# 결과 출력
print("대각행렬:")
print(diagonal_matrix)
print("벡터:")
print(vector)
print("곱한 결과:")
print(result)

대각행렬:
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
벡터:
[ 1  0 -1  2]
곱한 결과:
[ 1  0 -3  8]


In [39]:
# Q. 1부터 10까지의 숫자를 대각선에 갖는 대각행렬을 만들고, 그 대각행렬을 제곱하세요.
import numpy as np

a = np.diag([1, 2, 3, 4, 5, 6, 7 ,8 ,9, 10])
print(a,'\n')
b = np.square(a)
print(b)

[[ 1  0  0  0  0  0  0  0  0  0]
 [ 0  2  0  0  0  0  0  0  0  0]
 [ 0  0  3  0  0  0  0  0  0  0]
 [ 0  0  0  4  0  0  0  0  0  0]
 [ 0  0  0  0  5  0  0  0  0  0]
 [ 0  0  0  0  0  6  0  0  0  0]
 [ 0  0  0  0  0  0  7  0  0  0]
 [ 0  0  0  0  0  0  0  8  0  0]
 [ 0  0  0  0  0  0  0  0  9  0]
 [ 0  0  0  0  0  0  0  0  0 10]] 

[[  1   0   0   0   0   0   0   0   0   0]
 [  0   4   0   0   0   0   0   0   0   0]
 [  0   0   9   0   0   0   0   0   0   0]
 [  0   0   0  16   0   0   0   0   0   0]
 [  0   0   0   0  25   0   0   0   0   0]
 [  0   0   0   0   0  36   0   0   0   0]
 [  0   0   0   0   0   0  49   0   0   0]
 [  0   0   0   0   0   0   0  64   0   0]
 [  0   0   0   0   0   0   0   0  81   0]
 [  0   0   0   0   0   0   0   0   0 100]]


In [40]:
# 영행렬
import numpy as np

Z = np.zeros((3,3))

print(Z)

print(np.all(Z == 0))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
True


In [41]:
# Q. 영행렬을 정의하고, 임의의 행렬과 더한 후 출력하세요.
import numpy as np

# 3x3 영행렬 생성
zero_matrix = np.zeros((3, 3))

# 임의의 3x3 행렬 생성
random_matrix = np.random.rand(3, 3)

# 두 행렬 더하기
result_matrix = zero_matrix + random_matrix

# 결과 출력
print("영행렬:")
print(zero_matrix)
print("\n임의의 행렬:")
print(random_matrix)
print("\n더한 결과 행렬:")
print(result_matrix)

영행렬:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

임의의 행렬:
[[0.13450529 0.28113268 0.86232615]
 [0.16291781 0.05420119 0.13362899]
 [0.67636107 0.40471444 0.88711397]]

더한 결과 행렬:
[[0.13450529 0.28113268 0.86232615]
 [0.16291781 0.05420119 0.13362899]
 [0.67636107 0.40471444 0.88711397]]


In [42]:
# 전치
a = np.arange(9).reshape(3,3)
print(a,'\n')
a.T

[[0 1 2]
 [3 4 5]
 [6 7 8]] 



array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [43]:
#Q. 임의의 행렬을 생성 후 전치 행렬을 구하세요.
import numpy as np

# 임의의 행렬 생성
original_matrix = np.random.rand(3, 3)
print("원본 행렬:")
print(original_matrix)

# 전치 행렬 구하기
transpose_matrix = np.transpose(original_matrix)
print("전치 행렬:")
print(transpose_matrix)

원본 행렬:
[[0.76133651 0.74003271 0.38152485]
 [0.30394676 0.79131908 0.1781759 ]
 [0.55798713 0.14790211 0.94158826]]
전치 행렬:
[[0.76133651 0.30394676 0.55798713]
 [0.74003271 0.79131908 0.14790211]
 [0.38152485 0.1781759  0.94158826]]


In [45]:
# Q. 1부터 10까지의 숫자를 대각선에 갖는 대각행렬을 만들고, 그 대각행렬을 전치행렬로 바꾸세요.

a = np.diag([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(a,'\n')
b = a.transpose()
print(b)

[[ 1  0  0  0  0  0  0  0  0  0]
 [ 0  2  0  0  0  0  0  0  0  0]
 [ 0  0  3  0  0  0  0  0  0  0]
 [ 0  0  0  4  0  0  0  0  0  0]
 [ 0  0  0  0  5  0  0  0  0  0]
 [ 0  0  0  0  0  6  0  0  0  0]
 [ 0  0  0  0  0  0  7  0  0  0]
 [ 0  0  0  0  0  0  0  8  0  0]
 [ 0  0  0  0  0  0  0  0  9  0]
 [ 0  0  0  0  0  0  0  0  0 10]] 

[[ 1  0  0  0  0  0  0  0  0  0]
 [ 0  2  0  0  0  0  0  0  0  0]
 [ 0  0  3  0  0  0  0  0  0  0]
 [ 0  0  0  4  0  0  0  0  0  0]
 [ 0  0  0  0  5  0  0  0  0  0]
 [ 0  0  0  0  0  6  0  0  0  0]
 [ 0  0  0  0  0  0  7  0  0  0]
 [ 0  0  0  0  0  0  0  8  0  0]
 [ 0  0  0  0  0  0  0  0  9  0]
 [ 0  0  0  0  0  0  0  0  0 10]]


In [48]:
# Q. 대칭행렬을 생성하고 대칭행렬인지 확인하세요.
import numpy as np

def create_symmetric_matrix(n):
    A = np.random.rand(n, n)
    symmetric_matrix = (A + A.T) / 2
    return symmetric_matrix

def is_symmetric(matrix):
    return np.allclose(matrix, matrix.T)

n = 4
symmetric_matrix = create_symmetric_matrix(n)
print("생성된 대칭행렬:")
print(symmetric_matrix)

if is_symmetric(symmetric_matrix):
    print("이 행렬은 대칭행렬입니다.")
else:
    print("이 행렬은 대칭행렬이 아닙니다.")

생성된 대칭행렬:
[[0.07839243 0.72776232 0.51962675 0.66187382]
 [0.72776232 0.52602386 0.67446487 0.53755436]
 [0.51962675 0.67446487 0.1440023  0.91969095]
 [0.66187382 0.53755436 0.91969095 0.93666286]]
이 행렬은 대칭행렬입니다.


In [49]:
# 정방행렬
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [50]:
# 정방 행렬
a = np.full((2,2),7)
a

array([[7, 7],
       [7, 7]])

In [51]:
# 대각합 계산
np.trace(np.diag([2, 4, 6, 8, 10]))

30

In [52]:
# Q. 임의의 행렬을 생성후 대각합을 구하세요.
import numpy as np

matrix = np.random.randint(1, 11, size=(3, 3))

print("생성된 행렬:")
print(matrix)

trace = np.trace(matrix)

print("대각합:", trace)

생성된 행렬:
[[ 4 10  6]
 [ 7  1  5]
 [ 1  6  1]]
대각합: 6


In [54]:
# 역행렬
import numpy as np

A = np.array([[1,2], [3,4]])
print(A,'\n')

A_inverse = np.linalg.inv(A)

print(A_inverse,'\n')
print(A @ A_inverse)

[[1 2]
 [3 4]] 

[[-2.   1. ]
 [ 1.5 -0.5]] 

[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [56]:
# Q. 임의의 3x3행렬 의 역행렬을 구하여 출력하세요
def mx7():
    A = np.array([[1, 2, 3], [0, 1, 4], [5, 6, 0]])
    print(A,'\n')
    result = np.linalg.inv(A)
    print(result)
mx7()

[[1 2 3]
 [0 1 4]
 [5 6 0]] 

[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]


In [62]:
# 행렬식 결과가 0이면 역행렬이 존재하지 않는다.
np.linalg.det(A)

-2.0000000000000004

In [63]:
import numpy as np

# 상삼각 행렬 정의
A = np.triu(np.ones((3,3)))

# 하삼각 행렬 정의
B = np.tril(np.ones((3,3)))

# 상삼각 행렬 출력
print(A,'\n')

# 하삼각 행렬 출력
print(B)

[[1. 1. 1.]
 [0. 1. 1.]
 [0. 0. 1.]] 

[[1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]


In [64]:
# Q. 임의의 행렬을 생성 후 상삼각 행렬을 구하세요
import numpy as np

np.random.seed(0)
matrix = np.random.randint(1, 10, size=(5, 5))
print("임의의 행렬:")
print(matrix)

upper_triangular_matrix = np.triu(matrix)
print("상삼각 행렬:")
print(upper_triangular_matrix)

임의의 행렬:
[[6 1 4 4 8]
 [4 6 3 5 8]
 [7 9 9 2 7]
 [8 8 9 2 6]
 [9 5 4 1 4]]
상삼각 행렬:
[[6 1 4 4 8]
 [0 6 3 5 8]
 [0 0 9 2 7]
 [0 0 0 2 6]
 [0 0 0 0 4]]


In [66]:
# Q. 임의의 행렬을 생성 후 하삼각 행렬을 구하세요
import numpy as np

np.random.seed(0)
matrix = np.random.randint(1, 11, size=(5, 5))
print("원본 행렬:")
print(matrix)

lower_triangular_matrix = np.tril(matrix)
print("하삼각 행렬:")
print(lower_triangular_matrix)

원본 행렬:
[[ 6  1  4  4  8]
 [10  4  6  3  5]
 [ 8  7  9  9  2]
 [ 7  8  8  9  2]
 [ 6 10  9 10  5]]
하삼각 행렬:
[[ 6  0  0  0  0]
 [10  4  0  0  0]
 [ 8  7  9  0  0]
 [ 7  8  8  9  0]
 [ 6 10  9 10  5]]
